### ISSUE TITLE
reactors still sometimes make smoke

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#104]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Reactors still produce smoke when they are given uranium and havnt burnt any of it yet
![reactor smoking](https://github.com/user-attachments/assets/d7a490bb-de6d-4619-82e3-fc6a425dbce2)

### How can we reproduce this bug?

give a reactor uranium with the control rods at max

### Frequency

Always

**Comment by Hexcede** [comment]
This should be resolved, let me know if it isn't
