### ISSUE TITLE
chat commands dont work when your spamming

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#105]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

chat commands dont go through when the roblox chat spam prevention thing blocks your message.

### How can we reproduce this bug?

spam chat commands

### Frequency

Always

**Comment by Hexcede** [comment]
This isn't a bug, it's just how the Roblox chat works
