### ISSUE TITLE
Nightvision x Buttons Bug

### ISSUE THREAD

**Issue by tmenna1** [Eggs-D-Studios/wos-issues#106]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

you cant click buttons when you load them in

### How can we reproduce this bug?

 1. compile a button
 2. load it in and fail clicking it

### Frequency

Always

**Comment by Hexcede** [comment]
This isn't a bug, the model builder is just not set up to add components to the button. You need to add a `Configuration` instance called `ClickButton` inside of the button part. There will be an option in the model builder to automatically do this when I add component support to the plugin.
