### ISSUE TITLE
Ships leaping between regions

### ISSUE THREAD

**Issue by Pextri** [Eggs-D-Studios/wos-issues#12]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

When warping to a planet in unstable, you will spawn above the planet in space, attempting to enter your `Vehicleseat` will cause the ship to disappear and trigger your screen fading to black, bringing you to a inside the planet region without you directly flying to the planet. If the same is done to the same ship inside the planet, it will repeat the same in reverse, fading your screen to black and triggering an automatic teleport above the planet in space.

### How can we reproduce this bug?

1. Create a ship and warp to a planet
2. Suffocate in space and respawn inside your ship (you spawn in space after warp for some reason this is a bug that also needs to be fixed but thats not the main issue here)
3. Enter your `Vehicleseat` and proceed to get automatically warped inside the planet
4. Do the same inside the ship in the planet to replicate this bug but entering back into space instead

Examples of this happening for both planet and space
https://gyazo.com/d4ff354ece6e33d82c5a9e57bccf8b04
https://gyazo.com/488e7ebbb011cdac6f98f2bc37fbb7c4

### Frequency

Always

**Comment by Hexcede** [comment]
This should be resolved, let me know if it isn't
