### ISSUE TITLE
Cleaning service visual (?) issue

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#127]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

When the cleaning service gives parts the red box thing, the parts do not loose the box after being grounded and locked. I am not entirely sure this is a bug, but im fairly confident that this wasnt happening when you originally did the cleaner rewrite.

### How can we reproduce this bug?

wait for cleaning service to mark a part and then lock it

### Frequency

Always

**Comment by Hexcede** [comment]
This should be fixed, let me know if this is not the case
