### ISSUE TITLE
Beacon does not project light

### ISSUE THREAD

**Issue by Pextri** [Eggs-D-Studios/wos-issues#13]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

`Beacon` does not project a beam of light when powered, attempted to make it work with both a dev and normal power cell
![image_2024-04-30_185441495](https://github.com/Eggs-D-Studios/wos-issues/assets/102265930/77d95497-6e11-42a5-94ad-5beae683fe41)

### How can we reproduce this bug?

1.Attach a beacon to a charged powercell

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/b398cd04-b88d-45f2-9a18-20b8cec03b0f

this has been fixed
