### ISSUE TITLE
CJoints aren't treated as direct connections under some circumstances

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#138]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

With loaded models, under certain circumstances, a Wire will not receive power from power cells attached via CJoints. The bug occurs both when the wire is loaded with the CJoint already in place and when it is loaded without and the CJoint is added later.

In the following screenshot, the ropes connect the DevBatteries to the corresponding Wires. The left and the right component are identical, save for the Light being offset 0.5 studs in the right component (notably, in the left component, the Light's position is the same as the Wire's).

![image](https://github.com/user-attachments/assets/b381e15e-c010-4262-8653-eed8384913c4)

The expected behaviour would be for CJoints to act like direct connections all the time, i.e. for both Lights to be on in the above picture.

### How can we reproduce this bug?

1. Load the following model (the model from the above screenshot): [repr.txt](https://github.com/user-attachments/files/16619073/repr.txt)
2. Observe one Light turning on the other Light staying off.

### Frequency

Always

**Comment by Hexcede** [comment]
Can you check if this still occurs?

**Comment by RiskoZoSlovenska** [comment]
Yup, this looks to be resolved now; I'll close.
