### ISSUE TITLE
`GetPorts()` returns incorrect ports

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#142]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

With the following model,
![image](https://github.com/user-attachments/assets/f4b26a1f-6c4e-49e7-99ee-364f5cf77537)
the following code:
```lua
local function list(tbl)
	local buf = {}
	for i, port in ipairs(tbl) do
		buf[i] = port.PortID
	end
	return table.concat(buf, ", ")
end

print(list(GetPorts()))
print(list(GetPorts(1)))
print(list(GetPorts(2)))
print(list(GetPorts(3)))
```
prints:
```
3, 1, 2
1, 3, 2

3, 1
```
whereas the expected output would be
```
3, 1
1

3
```

Additionally, after poking Port 1 with the Drag tool (i.e. moving it away and then back), the code prints:
```
3, 1, 2
1, 2

3
```
which is still not correct.

### How can we reproduce this bug?

1. Load the following model: [getports repro.json](https://github.com/user-attachments/files/16635787/getports.repro.json)
2. Click the micro to run the above code
3. Observe the output in the F9 console

### Frequency

Always

**Comment by Hexcede** [comment]
This is intended behaviour, `GetPorts()` returns all accessible ports.

**Comment by RiskoZoSlovenska** [comment]
I can no longer reproduce this, closing as resolved.
