### ISSUE TITLE
Clicking on lines in the F2 history causes them to disappear

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#146]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Clicking on a line in the F2 console history log causes that line to disappear/become transparent/become empty. This also means that it is impossible to copy command outputs.

https://github.com/user-attachments/assets/d0f35406-fe8c-41eb-9b0a-6a70ef9346ed

### How can we reproduce this bug?

1. Open the F2 console
2. Run any command
3. Click on any line in the console except the one currently asking for input

### Frequency

Always

**Comment by Hexcede** [comment]
This doesn't apply to WoS, but cmdr, so if it is a bug it is a bug with cmdr upstream
