### ISSUE TITLE
being able to copy size of anything onto a part

### ISSUE THREAD

**Issue by ikwsgbygikwsg** [Eggs-D-Studios/wos-issues#147]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

https://github.com/user-attachments/assets/d025dfb3-a5a9-4805-a26b-fc12d20c3dad
able to copy the size of any part using the hammer size tool copy ability

### How can we reproduce this bug?

 Select a part then use the copy size ability on any part then reset (dont unselect part while doing so)

### Frequency

Always

**Comment by dogranger1** [comment]
this is related to https://github.com/Eggs-D-Studios/wos-issues/issues/429, which has been resolved.

https://github.com/user-attachments/assets/952b72b3-9ed9-4dc7-980b-78c2e50c4c07
