### ISSUE TITLE
make extractors have config again/ or mine every resource out of stone at once and disregard the one that has no destination (like refinery i think)

### ISSUE THREAD

**Issue by someoneidoknow** [Eggs-D-Studios/wos-issues#157]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Development (Unstable)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

since hexcede removed config, game balance was thrown out of the window because gasoline power legit became too incosistent to use due to random output

### What do you propose? What should change, or what should be added?

title basically

**Comment by madgarry105** [comment]
sorry

**Comment by eyecubed** [comment]
![allgamearebad](https://github.com/user-attachments/assets/6b39b839-ad23-4ec5-9e3f-4a58a2736a0a)

**Comment by Hexcede** [comment]
I didn't remove a config, refineries are not extractors, the output wasn't random, and this is not actually a feature suggestion this is a bug report
