### ISSUE TITLE
Teleporters are very broken

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#159]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Teleporters will teleport everyone in the region to their destination instead of just those standing on it. In region teleportation also appears to be broken.

### How can we reproduce this bug?

attempt to use a teleporter

### Frequency

Always

**Comment by Hexcede** [comment]
@L5108313 can you confirm that this has been fixed?
