### ISSUE TITLE
Give Tank the Resource config

### ISSUE THREAD

**Issue by 1-creare-1** [Eggs-D-Studios/wos-issues#166]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Staging)

### What happened? What did you expect to happen?

![image](https://github.com/user-attachments/assets/93178808-85c6-43e8-987a-786d4d9cfad2)

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/1c31f151-da3c-424a-8ad3-12e03231c5b0

this issue has been resolved (see video)
