### ISSUE TITLE
hammer broken

### ISSUE THREAD

**Issue by 1-creare-1** [Eggs-D-Studios/wos-issues#175]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Equipping hammer doesn't show ui

### How can we reproduce this bug?

no idea but here are the errors:
![RobloxScreenShot20240823_043546004](https://github.com/user-attachments/assets/6a39bf1b-960a-40d2-b4b7-2c0c45edcce0)

### Frequency

I can't make it happen consistently

**Comment by Joe-Derp** [comment]
I pushed a change which may fix this. Please let me know if this happens again.
