### ISSUE TITLE
Teleporters fail to teleport to other regions

### ISSUE THREAD

**Issue by 1-creare-1** [Eggs-D-Studios/wos-issues#178]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

When trying to teleport to a space region that contained our ship the teleporter had a red beam and failed to teleport us.

As a note, there is no receiving teleporter on our ship but assuming previous stable behavior it shouldve worked.

We were also able to rarely teleport however we couldn't reproduce it.

### How can we reproduce this bug?

Use teleporter to teleport to another region

### Frequency

Always

**Comment by Hexcede** [comment]
This should now be fixed
