### ISSUE TITLE
"Accidental Time Travel While Entering a Planet"

### ISSUE THREAD

**Issue by OKEMOWENDI** [Eggs-D-Studios/wos-issues#182]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

If you enter a starter on a ship, you will be in a separate server from the actual starter

### How can we reproduce this bug?

 1. Be in space over a starter with a working ship
 2. Enter the planet
 3. You spawn on the ground(which also shouldn't happen)
 4. Notice that there's only you in the server (I call the "Future" where you entered the planet)
 5. Your friend tries to join you through the main menu
 6. They join the "Main Server(the past where your ship didnt even exist yet)", which is populated
 7. You and your friends are both in the same coordinates

### Frequency

Always

**Comment by Hexcede** [comment]
This was resolved this morning, thanks for reporting the issue
