### ISSUE TITLE
Ships Spawns Too High

### ISSUE THREAD

**Issue by OKEMOWENDI** [Eggs-D-Studios/wos-issues#183]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Ships spawn so high when you enter a planet, such that if anyone sits on the ship it would just go back to space

### How can we reproduce this bug?

 1. warp into the planet
 2. spawn on the ground(shouldn't happen)
 3. respawn onto the ship with a spawnpoint
 4. sit on a seat attached to the ship
 5. warp back to space(shouldn't happen)

### Frequency

Always

**Comment by polikilopl** [comment]
can confirm, this happened to me as well

**Comment by TheBaconBoiUltimate** [comment]
please fix this asap
