### ISSUE TITLE
ocean water fog doesn't work

### ISSUE THREAD

**Issue by Erex147** [Eggs-D-Studios/wos-issues#192]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

underwater fog doesn't work anymore, normally if you go underwater a water coloured fog should appear and surround the player.
<img width="984" alt="Screenshot 2024-08-23 at 10 16 27 PM" src="https://github.com/user-attachments/assets/f759ea2e-b49e-466a-ada0-9de0bdfd093d">

### How can we reproduce this bug?

go into the ocean

### Frequency

Always

**Comment by khaopong23TH4** [comment]
I want it back

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/f0bcccfe-7cbe-4cf7-95db-385b9e574862

this bug is still valid (see video above)

**Comment by hail12pink** [comment]
duplicate
