### ISSUE TITLE
/vclean Doesn't Work

### ISSUE THREAD

**Issue by 1-creare-1** [Eggs-D-Studios/wos-issues#199]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Running `/vclean` in chat does not start a vote clean. "Rand vote clean command" does get sent in the console.

### How can we reproduce this bug?

1. Join Testing Zone
2. Say `/vclean` in chat

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/6f24f02f-6a20-4890-8350-b24fbdbce2a4

this bug has been fixed, as the command works again (see video). No error is displayed in the console.
