### ISSUE TITLE
Night vision goggles

### ISSUE THREAD

**Issue by suley135** [Eggs-D-Studios/wos-issues#203]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Night vision is unable to be removed, dissapears from inventory, and getting another takes it off but stops you from putting it back on.

### How can we reproduce this bug?

Equip night vision, disappears from inventory, make another night vision, equip that, it unequips the night vision but keeps the goggles on the face, and makes you unable to put them back on again.

### Frequency

Most of the time

**Comment by idfreud** [comment]
Can confirm, happened to me when exploring a night time planet.

**Comment by NameTemplate** [comment]
can confirm too
i think frequency is always, since it happens every time i wear night vision, unequip it, and dont take it off in a short amount of time.
