### ISSUE TITLE
I can't drag templates that were filled with material

### ISSUE THREAD

**Issue by tymbel** [Eggs-D-Studios/wos-issues#208]
### Guidelines

- [x] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I was making truss into iron mine and then I could not drag it once I make it iron or ANY other material

### How can we reproduce this bug?

 1. Spawn any template
 2. Insert any material
 3. You won't be able to drag it

### Frequency

Always

**Comment by Paxnar** [comment]
Idk if this is helpful or not, but after you move any other part, you can move the template again

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/cebf4cc7-9f36-4d61-9f75-7248c120b70c

As seen in the video, after the template has been filled with the iron, it can be moved. This has never happened to me so its probably fixed (since according to the report is always happens with the repro steps).
