### ISSUE TITLE
Loading models by roblox studio will sometimes make that model spawn anchored

### ISSUE THREAD

**Issue by notivan123234** [Eggs-D-Studios/wos-issues#215]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Staging)

### What happened? What did you expect to happen?

I loaded in a model with MBEE and it was anchored, i tried to drag and delete the parts but that didn't work.

### How can we reproduce this bug?

1. spawn a model with any model builder

### Frequency

Only sometimes

**Comment by dogranger1** [comment]
@notivan123234 please could you provide some reliable repro steps and at least some screenshots or a video. The code of the model you used would also be very useful.
