### ISSUE TITLE
Gravity gen should cancel swimming.

### ISSUE THREAD

**Issue by articlize** [Eggs-D-Studios/wos-issues#219]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Development (Staging)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

because underwater bases are cool.

### What do you propose? What should change, or what should be added?

so i can actually walk in my underwater base.

**Comment by hail12pink** [comment]
airlock mechanics already exist? is this a bug report?
