### ISSUE TITLE
dragger and crafting doesnt work every few minutes for about a minute.

### ISSUE THREAD

**Issue by articlize** [Eggs-D-Studios/wos-issues#220]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

very strange, theres a brief period every few minutes in which i just have to wait to move stuff around or craft for about a minute, its not 'lag' in the traditional sense since everything else is working fine?

### How can we reproduce this bug?

just play the game for a few minutes and you'll encounter it.

### Frequency

Always

**Comment by ItsJuanito101** [comment]
same

**Comment by ItsJuanito101** [comment]
i think its fixed now because hexcede worked on it

**Comment by orekay2** [comment]
configuring and interact also usually breaks during these lag spikes

**Comment by dogranger1** [comment]
i'm fairly certain that this bug has been fixed since i haven't encountered it once for the past few months. has anyone encountered this bug recently @orekay2 @ItsJuanito101 @articlize ?
