### ISSUE TITLE
Unwelded parts of ships warp with the ship for some reason.

### ISSUE THREAD

**Issue by DeviousLunatic** [Eggs-D-Studios/wos-issues#223]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When you detach parts from your ship, those parts warp away with your ship. What should of happened was that the detached parts stay in the planet or server.

### How can we reproduce this bug?

 1. Get two people.
 2. Warp to a planet.
 3. Have someone stay on the planet,
 4. Detach bins from your ship.
 5. Leave the planet.
 6. Observe.

### Frequency

Most of the time

**Comment by idfreud** [comment]
I was with OP when this happened. OP dropped me off on some planet with a couple of resource bins. When he left the planet the resource bins disappeared along with him. OP later returned to orbit and found the bins drifting in space.

**Comment by Joe-Derp** [comment]
having difficulty reproducing, tho big if true

**Comment by Joe-Derp** [comment]
nvm yeah this happens

**Comment by idfreud** [comment]
My guess is this only occurs if the server isn't restarted after the parts are unwelded.
