### ISSUE TITLE
Solar panels drain power instead of generating

### ISSUE THREAD

**Issue by notivan123234** [Eggs-D-Studios/wos-issues#227]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Staging)

### What happened? What did you expect to happen?

I attached a SolarPanel to a PowerCell and it started draining power, i don't know how this happened.

### How can we reproduce this bug?

1. spawn a PowerCell and a SolarPanel
2. attach the SolarPanel to the PowerCell
3. it should drain power

### Frequency

Only sometimes

**Comment by idfreud** [comment]
Was the panel facing the sun?

**Comment by hutek** [comment]
i think this also happens on stable

**Comment by Hexcede** [comment]
wow
