### ISSUE TITLE
NVG glued to unable to be taken off, assorted other bugs

### ISSUE THREAD

**Issue by ARandomShark2** [Eggs-D-Studios/wos-issues#229]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

A couple bugs. NVGs arent able to be taken off, they just stick to your face and you have to rejoin for it to come off. Has an 'A' next to it in steps.

Other bug is burning stuff to make glass, if the glass is locked, it wont be able to interacted with. Has a 'B' next to it in steps.

### How can we reproduce this bug?

1A. Craft NVGs
2A. Wear them, they should disappear from your inventory
3A. (Extra) Reset, the filter should stay. This was done on a starter world.

1B. Lock some sand
2B. Get a pile of Coal and burn the sand for glass
3B. attempt to move the glass, in my experience it wasnt able to be moved

KEEP IN MIND THIS WAS ON A STARTER WITH MANY PEOPLE ON IT, RESULTS MIGHT VARYING ELSEWHERE

### Frequency

Always

**Comment by Erex147** [comment]
can confirm the NVG bug

**Comment by Hexcede** [comment]
Please keep bug reports separate from eachother so I can track them properly

**Comment by Hexcede** [comment]
All of the mentioned bugs are fixed, but sand not burning into glass is intentional, it converts into glass at at 793.15 Fahrenheit.
