### ISSUE TITLE
Collisionless material/ Collisions off option for materials.

### ISSUE THREAD

**Issue by minediamondsss** [Eggs-D-Studios/wos-issues#23]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Development (Unstable)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

I think WoS lacks a material that players and ships could go through. I think such a material or an option for materials would be useful for designing - making fake water and those forcefield doors you see in docking bays in space movies. Collisionless materials would still take normal damage from guns and energy weapons.

### What do you propose? What should change, or what should be added?

Either a special material, preferably somewhat transparent, that does not collide with anything, allowing players and ships to go through it freely, or such option for materials already present in game.

**Comment by Pextri** [comment]
isnt this just what doors do, also lightbridges

**Comment by Hexcede** [comment]
> I think WoS lacks a material that players and ships could go through. I think such a material or an option for materials would be useful for designing - making fake water and those forcefield doors you see in docking bays in space movies. Collisionless materials would still take normal damage from guns and energy weapons.

The `Door` component definitely will do what you want already
