### ISSUE TITLE
warp takes no power

### ISSUE THREAD

**Issue by orekay2** [Eggs-D-Studios/wos-issues#231]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

warping requires no power and takes none

### How can we reproduce this bug?

1. warp anywhere
2. no power is taken

### Frequency

Always

**Comment by Hexcede** [comment]
I can't reproduce this

**Comment by orekay2** [comment]
strange, my setup is power cell connected to hyperdrive from wire
maybe try warping, then warping again if it breaks the cache in some way?

**Comment by orekay2** [comment]
seems it takes power sometimes, sometimes not, not sure what breaks it

**Comment by dogranger1** [comment]
![image](https://github.com/user-attachments/assets/6504731c-c3c3-4801-b680-19d627fe8cd2)

(image before warping)

![image](https://github.com/user-attachments/assets/0b7d4e98-37a6-48ad-9b1f-77fa85f27f72)

(image after warping)
