### ISSUE TITLE
Railgun does not function correctly

### ISSUE THREAD

**Issue by madgarry105** [Eggs-D-Studios/wos-issues#233]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I had set up a railgun as the main weapon for my ship. I had expected it to work correctly, firing a rail that penetrates a ship. However, the railgun instead freezes the server for a few seconds, then leaves a beam that cannot be moved or deleted.

![Black Beam1](https://github.com/user-attachments/assets/3ed95069-3ff6-4499-a6aa-6392aae8ab07)
![Black Beam2](https://github.com/user-attachments/assets/df438c60-d19c-44df-9209-2c88313a2f16)

Note the black beam is from the railgun with no other available source, railgun also does no damage.

![Screenshot 2024-08-25 at 3 31 06 PM](https://github.com/user-attachments/assets/02c4e79e-2f10-4f3c-a272-ee6565231b9c)

This shows me firing at a thing someone built and then never deleted, the beam simply destroyed a wall and froze. Maybe a bug related to how it is meant to penetrate parts?

### How can we reproduce this bug?

Joe should have the ship model if you need it, so you can ask him.

Due to another bug that seems to be related to power, it is a little difficult to set up. The general idea is you would fire the charged and loaded railgun, as intended, and it would not work correctly. I can confirm it is caused by firing at a large ship, so you would be better off setting up a railgun to fire at my ship model, since it can reproduce the conditions.

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/0f947b97-b953-4775-bbf4-8f58bf938f2a

pretty sure that this bug has been fixed, though there is another bug related to railguns and anchors (as seen in the final demonstration).

**Comment by ikwsgbygikwsg** [comment]
https://github.com/user-attachments/assets/eab6c92b-334a-46e4-9a21-098f6b742423

it be teleporting to a specific position

**Comment by dogranger1** [comment]
> 2024-11-28.17-41-49.mp4 
> it be teleporting to a specific position

could you please provide some repro steps to how to make the anchor red yet unanchored?

**Comment by dogranger1** [comment]
The follow-up bug has been fixed.
