### ISSUE TITLE
Model Imports Not Working

### ISSUE THREAD

**Issue by ItsJuanito101** [Eggs-D-Studios/wos-issues#234]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I click on model button i insert my data for the model and then i load it and it says "An error occured while loading the model: There isn't any save data for this model. Click Modify in the model options to give it some data." i tried every single way using the checkmark button clicking enter and i rejoined and it still doesnt work in every region

### How can we reproduce this bug?

Always Happens

### Frequency

Always

**Comment by Hexcede** [comment]
Hey @ItsJuanito101, can you provide steps to reproduce this issue? I understand that it happens consistently for you but I also need to be able to reproduce the issue to diagnose the problem

**Comment by Matrice300RTK** [comment]
> Hey @ItsJuanito101, can you provide steps to reproduce this issue? I understand that it happens consistently for you but I also need to be able to reproduce the issue to diagnose the problem

I have this same issue too, happens when I try to paste the raw or a link shortened version, really don't know the steps to reproduce it, but I do know the troubleshooting measures taken didn't work.

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/ace825c6-9db3-472c-b935-81182e313604

i've never encountered this bug before, perhaps there is a typo in the model builder code. could you provide some repro steps, @Matrice300RTK @ItsJuanito101 as well as some code for how this bug specifically occurs?
