### ISSUE TITLE
Temperature sensor proximity bug

### ISSUE THREAD

**Issue by Metirolous** [Eggs-D-Studios/wos-issues#236]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Whenever I come close to the reactor which my temperature sensor is controlling, it starts to take effect, however once I back away further, it stops, this has cause it to stay in its deficit/ increase forcing the reactor temp to either stay at 0 or have a meltdown. Other people seem to be having that problem too, saying they had reactors explode from temperature sensor not working properly.
I also saw someone in the WOS discord having the same proximity issues with their melters, stating that whenever they come close only then it starts to heat up.

### How can we reproduce this bug?

Create a basic reactor setup, 1 temperature sensor at 1:900 and another at 901:10000, make 2 poly silicones, deactivate/ activate respectfully to keep them at 1k range. Now step away from it, and wait for it to either cool down too much or have a meltdown

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/be07c634-5de4-43cd-8650-baffca35fe15

fairly certain that this has been fixed
