### ISSUE TITLE
Possible lag machine in -75, 50, 9, 1, false

### ISSUE THREAD

**Issue by Messyman200** [Eggs-D-Studios/wos-issues#237]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

The region is very laggy for seemingly no reason. I saw a structure close to the planet that might be a lag machine.

### How can we reproduce this bug?

1. Go to the region
2. High ping

### Frequency

Always

**Comment by Hexcede** [comment]
Hey, this isn't for reporting rule breaking. Also, most starter regions are currently pretty laggy and it's not because of lag machines.
