### ISSUE TITLE
Thruster/IonRocket deleting ship while in space

### ISSUE THREAD

**Issue by speeder5097** [Eggs-D-Studios/wos-issues#24]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

My ship erases itself and kills me when I put power into the the thruster or an Ion Rocket using a switch. It doesn't matter if I click the switch or activate it with a polysilicon. The thruster has a controller attached to it, but it doesn't matter which value the Controller is set to, the ship still erases either way. I have not testing if a gas powered Rocket will do the same.

### How can we reproduce this bug?

1. Make a ship with a switch to power a Thruster or IonRocket with a Controller touching the propulsion device
2. Warp to anywhere in space
3. Click the power for the Thruster/IonRocket, your ship should vanish and kill you, leaving you stranded in space with no hope.

### Frequency

Always

**Comment by Hexcede** [comment]
Can you provide a model that reproduces this bug in the form of an rbxm?

**Comment by Hexcede** [comment]
Not enough information to repro so I'm closing this issue, let me know if you have more information or open a new issue. Also, you may now submit a model as an unstable save rather than an rbxm if you have one.
