### ISSUE TITLE
the /c command crafts 2 items

### ISSUE THREAD

**Issue by notivan123234** [Eggs-D-Studios/wos-issues#251]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Staging)

### What happened? What did you expect to happen?

Using the /c command will craft 2 parts instead of one sometimes.

### How can we reproduce this bug?

1. use the /c command with any part

### Frequency

Only sometimes

**Comment by LuaBloxor** [comment]
duplicate of https://github.com/Eggs-D-Studios/wos-issues/issues/53
