### ISSUE TITLE
Rails break upon reload

### ISSUE THREAD

**Issue by D-7K** [Eggs-D-Studios/wos-issues#261]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When saving (leaving) a region, and rejoining, all rails cease to function. If they functioned correctly before, moving and responding to polysilicons, they do not do so after reloading

### How can we reproduce this bug?

Place a rail and place objects on the rail
Use a polysilicon on the rail to confirm it works
Leave and rejoin the game
Trigger the polysilicon again and see that it does not function

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/ae8878c3-8615-4894-a391-c26793f88ce3

pretty sure that this is fixed
