### ISSUE TITLE
Bins don't visually rust

### ISSUE THREAD

**Issue by 1-creare-1** [Eggs-D-Studios/wos-issues#269]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When damaging a bin to the point where it unwelds and unlocks it does not show any visible rust.

### How can we reproduce this bug?

1. Damage a bin to low health

### Frequency

Always

**Comment by Hexcede** [comment]
This is because bins don't take on a material, they have a texture. This isn't something I can realistically do anything about.
