### ISSUE TITLE
`part volume calculation` seem to be `taking into account the part shape`, is this a bug or intended behavior?

### ISSUE THREAD

**Issue by placeholder00** [Eggs-D-Studios/wos-issues#277]
old title: "`Thruster`(possibly other parts too) being `affected by shape type` (speed is affected in thrusters when set to cylinder shape)"

### Guidelines

- [x] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

In my use case, i wanted to test what would happen if i spawned a cylinder shaped thruster, but then noticed that speed does not seem to scale correctly while in the shaped form.

incase the region matters, i was in test server when i tried this.
i could not test it in survival as i havent left a starter yet.

Eg:
`fresh crafted thruster` sized to `16x16x16` with `100 propulsion` flies at `500 sps` (speed limit)
`"cylindrical" thruster` sized to `16x16x16` with `100 propulsion` flies at `~412.2 sps`
another `"cylindrical" thruster` sized to `16x8x32 with` `100 propulsion` flies at `~55.3 sps`

### How can we reproduce this bug?

1. spawn a `Thruster` and set its shape to `Cylinder`
2. compile and load ingame (again, `i have not tested this in survival` but i dont think it wouldve made a difference)
3. attach to some sort of setup
4. configure `Propulsion` to `100`
5. resize `Thruster` to desired size
6. activate the `"Cylindrical" Thruster`

### Frequency

Always

Edit:
a screenshot of a 3 powercells sized to 1x1x1, with shape type set to `Tetrahedron`, `Cylinder`, and `Default` respectively
![image](https://github.com/user-attachments/assets/c3c23b22-f5fa-4426-969d-1db8547a5243)

**Comment by Hexcede** [comment]
It took me a bit to realize but this has to do with Roblox's spacial audio feature, the audio is emitted from the surface of the shape. Therefore this is not actually a bug.
