### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by Pextri** [Eggs-D-Studios/wos-issues#28]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Both `screens` and `touchscreen` will project light, even when not active/powered

### How can we reproduce this bug?

Spawn a `screen` or `touchscreen` (preferably at night for clarity)
![image](https://github.com/Eggs-D-Studios/wos-issues/assets/102265930/1bab283e-3a71-4c1d-878b-e6b5505ed89b)

### Frequency

Always

**Comment by Hexcede** [comment]
A fix for this will be in the next unstable release
