### ISSUE TITLE
Part shift resilience (weld preservation for hand built/model loaded builds)

### ISSUE THREAD

**Issue by voidstonism** [Eggs-D-Studios/wos-issues#286]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

There is no point in trying to "Fix" part shift, its literally inevitable

### What do you propose? What should change, or what should be added?

Currently, hand build structures/ships eventually stop working after being part shifted a while, I do not know if that's the case for model loaded builds

Instead of trying to "fix" part shift, builds should still work or at least be more resilient to part shift. e.g. a button and trigger wire separated by 0.2 stud of part shift would still work due the welds being preserved. Weld preservation did exist in the old universe however it only benefited model loaded ship, hand builds would fall apart.

**Comment by someoneidoknow** [comment]
> ### Guidelines
> 
> 
> 
> - [X] I checked for duplicate suggestions
> 
> - [X] My suggestion intends to add or improve something
> 
> 
> 
> ### Version
> 
> 
> 
> Main (Production)
> 
> 
> 
> ### Topic
> 
> 
> 
> A game mechanic (e.g. a part, a feature, etc)
> 
> 
> 
> ### Why are you making your suggestion?
> 
> 
> 
> There is no point in trying to "Fix" part shift, its literally inevitable
> 
> 
> 
> ### What do you propose? What should change, or what should be added?
> 
> 
> 
> Currently, hand build structures/ships eventually stop working after being part shifted a while, I do not know if that's the case for model loaded builds
> 
> 
> 
> Instead of trying to "fix" part shift, builds should still work or at least be more resilient to part shift. e.g. a button and trigger wire separated by 0.2 stud of part shift would still work due the welds being preserved. Weld preservation did exist in the old universe however it only benefited model loaded ship, hand builds would fall apart.
> 
> 
> 
> 
> 
> 
> 
> 

how the hell would this work and micro wiring would literally explode, old universe had part shifted stuff still connected because it remade welds regardless of if the parts were connected

**Comment by Meowkitty-Hates** [comment]
Does He Know?!

He Doesn’t Know!
