### ISSUE TITLE
shape part bugs

### ISSUE THREAD

**Issue by Pextri** [Eggs-D-Studios/wos-issues#29]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

List of bugs that I have played around with and discovered:
A. Materials will get boosted to high/extreme temperatures after being inserted into a shape part
B. shape part will sometimes delete after being dragged if they are not connected to a material on release
C. shape part will become undraggable after being inserted into a material

### How can we reproduce this bug?

 A. 1. Insert any material (ex: `Iron` into a shape part like wedge/cylinder)
2. Note change in temperature

B. 1. Drag a shape part around without inserting it into a material and release your drag (seems to occur mostly on templates like cylinder, door, and maybe some others)
2. If it poofs from existence after you stop dragging it then that is bug in question

C. 1.Insert a part or material into a shape part
2. Attempt to drag the part after it has changed into the shape (multiple attempts might be needed for this one)

### Frequency

Only sometimes

**Comment by Hexcede** [comment]
> Materials will get boosted to high/extreme temperatures after being inserted into a shape part

This specific one is not a bug, it's just because the heat capacity of the part changes and because the template part's heat gets rebalanced into the other part.

The other two things are definitely bugs though

**Comment by Hexcede** [comment]
These bugs are fixed
