### ISSUE TITLE
GetPart..(port, [part]) doesnt work

### ISSUE THREAD

**Issue by anonymousomeone** [Eggs-D-Studios/wos-issues#291]
### Guidelines

- [X] I checked for duplicate bug reports
- [x] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Micro > Port > Ethernet > Port > Part

```lua
function GetPortByID(ports, id)
	for i, port in ports do
		if port.PortID == id then
			return port
		end
	end
end

local ports = GetPartsFromPort(1, "Port");
local port = GetPortByID(ports, 2);
local light = GetPartFromPort(port, "Light");

light:SetColor(BrickColor.random().Color)
```

model code:
```json
{"m":null,"t":"buffer","zbase64":"KLUv/WD1Bt0dAAZxqUYAc5wD/N/1EgUAAED1AaAoAACAAkBXIeAAfVp0E4mjSm9MEl2EnY6Jdju28G8Pr+Jmqq4d8JZQWmaVqWpoe2h8ebX73UgKlgCfAJMA2Zb5tozztZOtinq/2V2vyroDdDgcAI2mO8Tz0ZhuTsOIgYHPxiMCMjct6+6NpttA/Spm3Vom47ozGkzW3Zmmu9PdHkJ090dDxLuvvy9H943u/mz8+PHj+z7dHu3O8e3o9j4v1o2jRbcp1u11i0XoxbxYjhbdJycnM1Zk8GIi2ot16yDBahE8etRAfU5U9KZ7I6M7c9EdJTFQUEikzMRFjMq07+M8vPVLm1oJLYmCUUuybtB1qS/wovhcH+xYKEWoQOqykyTOf3GIc2hLPhguUJiwTYxHlOnu0gWL1QVm23divNWEU5Z+3zXafMo4ER5oEEIOQO8arYnNiATaYACIyJYBLci8ZP+vpxZPcRQkQHAAZGI8BTqp1WfMygBsIZ8xSyMwQABIE/Id8GxzbloGCqB1vg8XXtKXFnWyVUsr0u4zfrGs6HjtSuiu0F8vKSi2IuxBSiJN8fpIVJK1hUmSd5LSKGWkwkw8Ji2rNILioW3JDv7L5hDM3pIdLDlLHUWeLeyFZ1NqdWEmqRUM3BJvBbuX+yn7ONqcwlMu4vCqTqAAS3Sfcdl9xiwWnEd8rqx3Enrd9dTD+ipXMnahKnampJikSJBUKtUpIlrW3RiMx0NGC+l04LABND0ZRqWRiAWLt+bSSmjzSZQxiVHv4Ic5QYxCIdq5RktiADEKfcasEO0uiEy0JGuIyTnF61O8znEzw94zx3HzuuupaKnJREsqluMmFml5Lf2MX7SzNGMVbo5ES7vyM36JUquX02eM7YcXpjJLFih+WmYXL4z6w1o2/1fqrqfjtf8BgJCo8SSESg3JSJAkBSVJB8ACqapRBxEgUAmtCWZEaIqK2Q6uu73xiZj4SxmUUb2pWCpNmjdDFsGWwidxnK+D5Hj0NfG3VcGNMuJe/ttuHDFEatu0iNGmRk0f29MoK/x/iOdXUPG/ovviPa8tITFNobRisR4F4L4R1cFnldiBzI6OuGrya2MIuA1LA2j0sOYsiFoE4OFeueiEQ/Rw809VBQqMLA0EGb+4ZVpClSoUcwNUPFyIzDXIBPib1tb1SDFmNJ+qwDMJQjMgiwIOw2R5JhkpvIKAorfcFLSbkVaHsW0KEmF+Xn3pZXav1yWIX5RegfGaOlE0Y5b+TkVaYEGzfDIT5wzik/b/nMevc0qgYcqKQho="}
```

### How can we reproduce this bug?

1. load in the model
2. click the micro
3. profit

### Frequency

Always

**Comment by 1-creare-1** [comment]
I'm also encountering this issue
```lua
local repr = require("repr")

local port = GetPort()
print(repr(port))
print(repr(GetPartFromPort(port, "Reactor")))
```
The port exists however `GetPartFromPort` fails to get the reactor thats connected to the port

`Microcontroller -> Ethernet -> Port -> Reactor`
![image](https://github.com/user-attachments/assets/ff4d1e39-2e82-4fa9-8a5f-5e57e0693304)

**Comment by 1-creare-1** [comment]
It appears to work when the layout is changed to `Microcontroller -> Ethernet -> Port -> Ethernet -> Reactor`
![image](https://github.com/user-attachments/assets/38574c22-c842-408f-a137-2f09575068a1)

**Comment by anonymousomeone** [comment]
real engine

**Comment by CL-2812** [comment]
I tested the model anonymousomeone provided, and the issue appears to be fixed. @anonymousomeone please double check and close the issue if it's fixed.

For 1-creare-1, your code doesn't work probably because it was returning the port attached to the micro.
Try printing port.portID to confirm this.

**Comment by anonymousomeone** [comment]
fixe

![image](https://github.com/user-attachments/assets/3dc6fa89-5c02-4878-bce7-21e391596e1b)
