### ISSUE TITLE
Kiln is not smelting

### ISSUE THREAD

**Issue by GreatBoblox** [Eggs-D-Studios/wos-issues#297]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

My kiln does not convert sand into glass even when the empty bin is named "Glass".  https://discord.com/channels/616089055532417036/1278114335016620135/1278114335016620135

### How can we reproduce this bug?

 1. Warp to space.
 2. Warp back to the planet.
 3. Warp to space again and repeat until something happens.
 4. Sometimes, your ship will disappear or be duplicated.

 1. Set up a `Filter` for `Sand` that's attached to a `Kiln` and a `Sand` bin.
 2. Turn on the `Kiln` and observe that it can't find the `Sand`.

### Frequency

Always

**Comment by Yeetano** [comment]
Do you have a bin for output that is configured to “Glass”

**Comment by Hexcede** [comment]
Try to keep issues separate so I can track them better in the future. Both of these should be resolved as of a while back though so no need to open any new ones or anything
