### ISSUE TITLE
microcontrollers consume all available power when on 

### ISSUE THREAD

**Issue by Saturn-Titan** [Eggs-D-Studios/wos-issues#298]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

whenever i turn on my microcontroller for my auto reactors, it just consumes any and all available power while also doing nothing. I expected the microcontroller to just take maybe 1 power a second. using a sorter doesnt work either, it still bypasses it and consumes everything.

### How can we reproduce this bug?

1. put down a micro controller
2. put some code in it
3. power

### Frequency

Always

**Comment by Hexcede** [comment]
@Saturn-Titan Can you provide me with the code that produces this issue on Discord?
