### ISSUE TITLE
ctrl + delete will often delete parts not highlighted.

### ISSUE THREAD

**Issue by articlize** [Eggs-D-Studios/wos-issues#299]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

moved some bins of my factory assembly, to replace it with a new one. used ctrl to delete it and it clearly did not highlight the bins detached bins, but removed those with it.

### How can we reproduce this bug?

move something of an assembly and then ctrl delete it.

### Frequency

Always

**Comment by Hexcede** [comment]
@articlize This should now be fixed as of the last update, let me know if you encounter this again
