### ISSUE TITLE
Ship gets tped after entering a planet(it was reported on staging so its kinda a re-report)

### ISSUE THREAD

**Issue by MoonDark0** [Eggs-D-Studios/wos-issues#307]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

My ship gets teleported out after entering a planet

### How can we reproduce this bug?

Enter a Planet

### Frequency

Always

**Comment by HDMICIDE** [comment]
I experience the same issue but only when im using a thruster instead of an ion so im going very fast, going in from the side of the planet or spam jumping when you load in then unanchoring then sitting when youre below space work well

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/be999331-33e9-448e-898c-5861d8ca2c0f

this has been fixed
