### ISSUE TITLE
Cannot load to planet, "please check your internet connection" but i have stable connection

### ISSUE THREAD

**Issue by mettanol** [Eggs-D-Studios/wos-issues#309]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

trying to load in a planet, results in error after main loading screen.
![image](https://github.com/user-attachments/assets/64964d7a-69f6-437e-9746-b272905d8da6)
i do have stable internet connection, nor me and my friend can join. this bug happened earlier, but it fixed itself after some time, so i decided to not write a bug report. there is also a chance that you can not even load, with an error 
![image](https://github.com/user-attachments/assets/9ae25850-1c67-4e44-a57d-1fd7e5b9439d)

### How can we reproduce this bug?

 1. Load to planet
 2. Disappointment

### Frequency

Most of the time

**Comment by mettanol** [comment]
forgor console log
![image](https://github.com/user-attachments/assets/eaa4cec4-5014-4b3d-ab22-8f16ae353525)

**Comment by Hexcede** [comment]
This is caused by the Roblox server crashing and isn't a WoS bug it's a Roblox bug. There isn't much I can do about it.
