### ISSUE TITLE
/ to chat does not work

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#313]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

pressing / does not enter the chat textbox. I had assumed it was somehow a sober thing since nobody was complaining, but i asked someone and apparently everyone has this issue. 

### How can we reproduce this bug?

press the / key

### Frequency

Always

**Comment by Hexcede** [comment]
@L5108313 This should be fixed now, let me know if it's not
