### ISSUE TITLE
ARControllers CursorPressed callback doesn't call the provided function

### ISSUE THREAD

**Issue by patc4** [Eggs-D-Studios/wos-issues#314]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

the code provided does not print in the console "click"

### How can we reproduce this bug?

run the following code in a microcontroller with a port attached to an ar controller

```
local ar = GetPartFromPort(1, "ARController")

local function processClick(cursor)
  print("click")
end

ar.CursorPressed:Connect(processClick)

while true do
  task.wait(1)
end
```

### Frequency

Always

**Comment by patc4** [comment]
just to follow up on this, it's doing the same with this code too.

```
local p2 = GetPort(2)
p2.Triggered:Connect(function() print("triggering!") end)
```

**Comment by Hexcede** [comment]
@patc4 can you check whether or not this issue still happens?

**Comment by patc4** [comment]
the ar example still doesn't work, but the button example works now.
