### ISSUE TITLE
Resizing apon sand lags the game REALLY hard for some reason, does not happen on grass.

### ISSUE THREAD

**Issue by NoobieOofguy** [Eggs-D-Studios/wos-issues#317]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Putting something onto sand and try to resize it, at least on the starter im on, it lags the game REALLY HARD man. (Uzufi Alpha 90, -22, -6, 5)
All i was trying to do was make a simple glass production thingy lol

The video here, the really sped up part is the lagging... For some reason thats how roblox screen record works, speeds up lag
https://github.com/user-attachments/assets/0da631c5-4e0f-426a-a76d-392b921c5a36

### How can we reproduce this bug?

1. Put something onto sand, anything will work
2. Attempt to resize
3. Enjoy the lag that comes with it for some reason

### Frequency

Always

**Comment by madgarry105** [comment]
so fake
