### ISSUE TITLE
cannon does spawn but not propel pellets

### ISSUE THREAD

**Issue by GooberGoonie** [Eggs-D-Studios/wos-issues#319]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

cannon doesnt shoot but spawns pellets

### How can we reproduce this bug?

spawn cannon 
put cannon on copper bin
shoot cannon

https://github.com/user-attachments/assets/4a38dfb3-34e9-4dfb-a6db-671c990b52a4

### Frequency

Always

**Comment by Hexcede** [comment]
This is hilarious
