### ISSUE TITLE
Ship Bugged in Hyperdrive

### ISSUE THREAD

**Issue by riptidemamba** [Eggs-D-Studios/wos-issues#321]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Went into hyperdrive while facing upwards and the ship bugged. My fov didnt expand as it usually does in hyperdrive, but the sound play

### How can we reproduce this bug?

1. Get a ship on Guzisuj Omega (29, -2, 1, -10)
2. Warp to space coords

### Frequency

Always

**Comment by Hexcede** [comment]
I couldn't reproduce this issue, could you provide some more information? @riptidemamba

**Comment by madgarry105** [comment]
just eated it.... proof pl0ox
