### ISSUE TITLE
You can weld stuff onto tree leaves

### ISSUE THREAD

**Issue by NameTemplate** [Eggs-D-Studios/wos-issues#324]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

You can weld parts on tree leaves, even though tree leaves change rotation and size and stuff every server reload. When something is welded on the tree leaf and you reload the server, it unwelds and falls off, giving no reason for the leaves to be weldable. Problem is, due to being able to weld things on tree leaves, you cant put stuff inside the leaf, so you cant hide a base inside a tree. I think this is a bug because you weren't able to weld things on tree leaves in the previous update (iirc)

### How can we reproduce this bug?

1. Go to tree
2. Weld part (grass, wood, whatever) onto tree leaf

### Frequency

Always

**Comment by NameTemplate** [comment]
it seems the welding on leaves part is fixed, but it still stops from being able to weld things to stuff inside tree leaves (which you can do either by resizing it into the tree leaf or putting it in a place without tree leave but where a tree leaf can be and rejoin to make the tree leaf randomize again)

i hope this wont require something like modifying the drag tool code or something

**Comment by NameTemplate** [comment]
> it seems the welding on leaves part is fixed, but it still stops from being able to weld things to stuff inside tree leaves (which you can do either by resizing it into the tree leaf or putting it in a place without tree leave but where a tree leaf can be and rejoin to make the tree leaf randomize again)
> 
> i hope this wont require something like modifying the drag tool code or something

the reason i'm making this bug report is due to it interfering with my treehouse, after all.

**Comment by Hexcede** [comment]
Trees are not supposed to be different when you reload the region

**Comment by NameTemplate** [comment]
> Trees are not supposed to be different when you reload the region
wait so the position of the branches and leaves werent supposed to constantly change?

**Comment by NameTemplate** [comment]
The main issue i had with this was the inability to move things inside the leaf (can't make things go in it, can't drag something that is already in it without taking it outside, then you can't put it back in) with the drag tool. However, it seems this problem is from the dragger instance according to https://github.com/Eggs-D-Studios/wos-issues/issues/451#issuecomment-2385778073 and cant be fixed without completely rewriting the hammer code. I'm likely to close this but I'm gonna wait for a confirmation.

**Comment by dogranger1** [comment]
Load 1:

![image](https://github.com/user-attachments/assets/f3e5ee3f-ffaf-4fc5-99c3-80cf4a1850e3)

Load 2:

![image](https://github.com/user-attachments/assets/753a4e27-6d1d-412e-9325-24722b7797f5)

Load 3:

![image](https://github.com/user-attachments/assets/5d8c1bfe-e550-4be8-9026-abc0e0efaac7)

Can no longer weld parts onto trees (as you mentioned).
