### ISSUE TITLE
Fly and spawn command permissions are broken in cmdr

### ISSUE THREAD

**Issue by orekay2** [Eggs-D-Studios/wos-issues#326]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

normal players are unable to use spawn (makes spawning bins of resources easier)
and unable to use fly (just generally useful)
cmdr complains about security level
example below
![image](https://github.com/user-attachments/assets/445bb931-e204-4c26-b900-b15f029574eb)

### How can we reproduce this bug?

1. be a regular user (not mod or dev)
2. attempt to spawn or fly
3. fails due to permissions

### Frequency

Always

**Comment by Hexcede** [comment]
This should now be fixed as of the last update @orekay2
