### ISSUE TITLE
Model loader is slow

### ISSUE THREAD

**Issue by 0mori1** [Eggs-D-Studios/wos-issues#327]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When model loader draws parts from a physical source [like an unlocked bunch of parts], it does that so slowly it exhausts its allowed execution time

### How can we reproduce this bug?

Load a model like the puter in once, load in the perfectiumcore to power it, realize that you didnt lock the puter and the antenna is now missing from it, load the puter back in, wait 10 years, whoops its broken and you can't fix it in any way other than rejoining 

### Frequency

Always

**Comment by 0mori1** [comment]
yes i know some other guys reported this bug too

**Comment by Hexcede** [comment]
@0mori1 can you check if this is resolved?
