### ISSUE TITLE
Assembler Breaks with no assemble value

### ISSUE THREAD

**Issue by riptidemamba** [Eggs-D-Studios/wos-issues#328]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

If you power an assembler to a chute connected to tons of bins and it doesnt have an Assemble value, but then you set the Assemble value after, it attempts to craft that thing 3 times before failing and effectively wasting those resources used.

### How can we reproduce this bug?

1. Put an assembler next to bins with chutes
2. Have a switch on the assembler, leave it off
3. Set assemble value to nothing
4. Power the assembler
5. Set assemble value to something that can be assembled
6. Boom

### Frequency

Always

**Comment by Hexcede** [comment]
This is not a cache issue

**Comment by Hexcede** [comment]
It is resolved though
