### ISSUE TITLE
Can't Craft from your own bins

### ISSUE THREAD

**Issue by riptidemamba** [Eggs-D-Studios/wos-issues#329]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Not sure how to replicate this exactly but sometimes when I go far away from a bin and come back I just cannot craft from it. Or bins I haven't used in a while. CanCraftFrom was true

### How can we reproduce this bug?

1. Lock a bin under your name
2. Attempt to craft from it.

### Frequency

I can't make it happen consistently

**Comment by Hexcede** [comment]
This bug is likely related to the same bug that caused the weld/location data soft-corruption issue and might be fixed as a result. Let me know if you encounter this again, I'll also watch out for it.
