### ISSUE TITLE
Hyperdrive Lag

### ISSUE THREAD

**Issue by riptidemamba** [Eggs-D-Studios/wos-issues#330]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Hyperdrives usually haves a massive delay before actually teleporting you, sometimes they never even teleport you. Happened to me ~3 times

### How can we reproduce this bug?

1. Have a ship with a Hyperdrive (in/out or orbit)
2. Warp
3. Sometimes it will take a while and sometimes it will just never work

### Frequency

Most of the time

**Comment by Hexcede** [comment]
This is an issue with Roblox and there isn't anything that can be done by us to resolve it
