### ISSUE TITLE
Weird Cloning Bay Behavior

### ISSUE THREAD

**Issue by riptidemamba** [Eggs-D-Studios/wos-issues#333]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

If your cloning bay is destroyed you just continue to respawn in that area even if its wild space. My original cloning bay was destroyed in -20, -40 and I still get the option to spawn there.

Please add some sort of system that makes your most recently crafted cloning bay your current one, or allow several

### How can we reproduce this bug?

1. Place a Cloning Bay on ship
2. Destroy the ship somewhere in space (destroy the cloningBay too)
3. Go to a starter and reset
4. Boom

### Frequency

Always

**Comment by Hexcede** [comment]
This is sort of due to how `CloningBay`s work but its been a thing since forever basically. I am looking to add support for having multiple cloning bays at which point this will also be resolved.
