### ISSUE TITLE
starmap stars mode issue

### ISSUE THREAD

**Issue by ryulet2** [Eggs-D-Studios/wos-issues#344]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

i was on a star seing my starmap on the stars mode, it was showing only 3 stars and then i warped to another star near by, the star that i was vanished from the map and it showed up about 5 new stars on the area

### How can we reproduce this bug?

1. go to a star where you see almost no stars near by.
2. warp to the only star that you can see.
3. check the starmap if there is extra stars where you were and if the main star desappeared

### Frequency

I can't make it happen consistently

**Comment by Hexcede** [comment]
I believe you just inputted part of the system coordinate incorrectly and ended up in a completely different solar system

**Comment by Hexcede** [comment]
I am closing this just so that other new reports can be made
