### ISSUE TITLE
Coupler Shift

### ISSUE THREAD

**Issue by hutek** [Eggs-D-Studios/wos-issues#346]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Bug 1: I was using a coupler to attach my cargo to my ship, and left the game. Upon rejoin, the ship had position shifted half-into the ground and rotated 90 degrees. The coupler that the ship had also position-shifted, but not as far as the ship did and did not rotate 90 degrees. I can DM you a 
screenshot since it contains planet-incriminating info, but for now here's a mockup of what happened. 
![image](https://github.com/user-attachments/assets/db6fbfe2-f0f8-4cc7-8f7c-ad70bb15da4f)

It seems as if the detached coupler is still welded to the ship, as when I unanchored the ship, the coupler moved with it. The coupler is also disconnected.

Bug 2: Things with couplers void while changing regions
I was going to space with my cargo thingy connected to my ship and it just... dissapeared when i went to space. I have a video of it occuring that I can dm you (also planet-incriminating info).

### How can we reproduce this bug?
bug 1:
1. Connect 2 unanchored assemblies with Coupler.
2. Rejoin region
3. Profit

bug 2:
1. try to go to another region with a coupled thing
2. profit

### Frequency

Always?

**Comment by hutek** [comment]
wait how do i edit issues i sent without describing bug 2 on accident

**Comment by dogranger1** [comment]
bug number 2 is a copy of https://github.com/Eggs-D-Studios/wos-issues/issues/399

**Comment by hail12pink** [comment]
please also don't report 2 different bugs on the same issue it's messy and confusing and bad

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/55c44b87-4955-4212-bfd5-7c6937a30e91

pretty sure that this has been fixed, though it may be a bug and the repro steps may not be detailed enough. perhaps you could send a dm to either "dogranger1" or "hexcede" on discord with the screenshots
