### ISSUE TITLE
2 hammer modes at the same time

### ISSUE THREAD

**Issue by sweetboss12512** [Eggs-D-Studios/wos-issues#35]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Sometimes when i equip and change mode quickly it's on drag and the other mode. like drag and configure, or drag and resize

it is big pain

https://github.com/Eggs-D-Studios/wos-issues/assets/101525599/a38692d2-4c24-4c4f-8d24-a6a033d466c8

### How can we reproduce this bug?

equip hammer then press Q or E right after

### Frequency

Most of the time

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/76662154-fc60-44a8-b0bc-3a654ac44a58


i'm pretty sure that this bug has been fixed, since not a single attempt at replicating this bug worked (as seen in the video above)
