### ISSUE TITLE
Assembler:Craft(int amount) bool Crafting , Assembler:CanCraft() bool

### ISSUE THREAD

**Issue by someoneidoknow** [Eggs-D-Studios/wos-issues#351]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A programming feature (e.g. APIs, tweaks, changes, etc)

### Why are you making your suggestion?

Allows for consistent crafting even if the game might lag spike a bunch

### What do you propose? What should change, or what should be added?

Would basically allow crafting a set amount of items or checking if we can craft an item, etc
would go hand in hand with a future ``recipes`` library

**Comment by 1-creare-1** [comment]
How is this different from the current
`Assembler:CraftItems({ string } | { [string]: number } items)`
and
`Assembler:CalculateCraftingRecipe({ string } | { [string]: number } items) → { Power: number, [string]: number }`

https://arvidsilverlock.github.io/Pilot.lua-Luau-LSP/docs/Programmable%20Objects/Assembler

**Comment by someoneidoknow** [comment]
those exist? oh well
