### ISSUE TITLE
Port vs Microcontroller GetPart() exclusivity issue

### ISSUE THREAD

**Issue by CL-2812** [Eggs-D-Studios/wos-issues#355]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

If a part is welded to both a port and a microcontroller, said part could only be accessed by GetPart()/GetParts() function. GetPartFromPort()/GetPartsFromPort() returns nil.

### How can we reproduce this bug?

See below model
`{"m":null,"t":"buffer","zbase64":"KLUv/WB6BS0VAJZebUUAcZwO/C4BACBo/UuvSEBVlQMAAACC9e+p081CtEuwqm+doD8btlavgzzUO13PsYeZsr2LOUeq6B/WK/DH0QzL52WzMgVRAFcAYQBg//Jq7b+wSv9vbPtPu64zUeKb4xwn/YcMGyPjP1NIWtCg/1PGt35jjvRzbKX8hzH+rfHvuq6jjuj/+Z/Sz/EvvXBxwjRyjzGDRLr8pcjfIX+hbEOs6rMqeEstKdXqZ728Ck0qvlAssfBOfbVF8VQoOyJjL6Nas2ECZC79/+LQX8NVFC/O9n4Xf+Gp/42Ho1kw7PfMGq/8GgeSAgEAPp1NJvu/xP6Pl70NGNib88kHCwhogcemtwSczq4fvCfWZ+vJiopL+r8ckAYK9P8Kdo29XyiGK5Z4uUwHAgIDMA/l6HyyTSabQ2500xiGZqKQCIRvis+SgDxGICFQxpdLXVySscflGkIDXUQBHWoSkfHl2iI9ZHw5OUdEOnyyimbDBVYNs2HIWDRkuBCCeTILUtTbh0W5JlY1ySp4T6tVxVz/QqKfwxSI/mUF70n0LIoQ1ZgJEkSjCCEOBLmxqkmFBxQcrLKt9qpSt9SYgIOo8TQpEc2IpE2lNfCiouE8ETBIKa0RCWRmSgpSyHTgF8Pmo+Ck5GZmOEm7d5M/qCXdzthE21tr57rF1AjJh4xNAVOTduy7i3OqK1OGpiWVO/4YnVFnIcHPo54I+nP8jXjVUM7TF4UjIjijXCOj+9vO06wZUhoIyM45sG0BjhEarUqdkwvnLvWZskAlcGCYCk6eX4wYPyI7c4qWtROgxNloi67m/t3yCj/yWfdri4DclXDLBccIRMV1QhZ1XnDS5hT2U2tOOas1ECOKIfVjslW10yCmfDP0xHEW9VJiPYgNFG3DxikLaEpZO68C"}`
with code
```
print()
print("	GetPartFromPort")
print(GetPartFromPort(1, "Anchor"))
print("	GetPart")
print(GetPart("Anchor"))
print()
```
and diagram
![image](https://github.com/user-attachments/assets/0c9c42c6-66e5-4903-b14b-fb0f238bc326)

1. Spawn model
2. Click button
3. Observe F9 console output

Expected buggy output:
![image](https://github.com/user-attachments/assets/1cb23072-275a-4e6e-82b9-b79a178c368f)

### Frequency

Always

**Comment by CL-2812** [comment]
This issue caused one of my builds to stop working after the 2024-09-04/05 hotfixes. I'm not sure if the exclusivity exists in a reversed state (GetPartFromPorts() above GetParts()) prior to the hotfix.

I'm fairly certain that this issue is unrelated to welding.

**Comment by 1-creare-1** [comment]
This may be related to https://github.com/Eggs-D-Studios/wos-issues/issues/291

**Comment by Hexcede** [comment]
I'm betting this is wire cache related. I'll check it out.

**Comment by RocketsSpace** [comment]
FINALLY
