### ISSUE TITLE
Radar [Metal]Deposit isn't functioning

### ISSUE THREAD

**Issue by Dusternboo** [Eggs-D-Studios/wos-issues#360]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Radar [Metal]Deposit on Gyro isn't aiming at deposits, instead acts similar to PointAfter 0,0,1 and rotates to make green arrow go under the gyro.

![Screenshot_49](https://github.com/user-attachments/assets/a8bbc89f-07f6-44d0-802d-83715d24fdf4)
![Screenshot_50](https://github.com/user-attachments/assets/2f2f0a3d-484a-4d37-bceb-00b72bbdd2a9)

### How can we reproduce this bug?

 1. Configure Gyro "Radar IronDeposit" (Iron being an example)
 2. Power it

### Frequency

Always

**Comment by Hexcede** [comment]
@Dusternboo Hey, could you check if this is resolved now?

**Comment by Dusternboo** [comment]
Sure, though it will take a while for me to not disconnect in game

**Comment by Dusternboo** [comment]
Yup
![Screenshot_58](https://github.com/user-attachments/assets/afda5f5f-243d-4a6f-a7df-6d827aa6f27d)
