### ISSUE TITLE
`CombustionTurbines` continue to generate heat after being cut from a fuel source

### ISSUE THREAD

**Issue by iiCove** [Eggs-D-Studios/wos-issues#361]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

After fueling a `CombustionTurbine` briefly, it will continue to generate heat as if it's running even when disconnected from it's fuel source.
It should stop generating heat when cut from fuel, as it stops generating power.

### How can we reproduce this bug?

1. Set up an `AirSupply`, a `CombustionTurbine` and a small amount of gasoline (I used 5 units in testing)
2. Attach the tank of gasoline to the `CombustionTurbine`. Let it deplete entirely.
3. Observe as the temperature continues to climb, even though the turbine has exhausted it's fuel and is no longer running.

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/347b579b-eca9-426a-b14b-0ca931f07398

(no longer a bug)
