### ISSUE TITLE
driveboxes load incorrectly

### ISSUE THREAD

**Issue by purobros** [Eggs-D-Studios/wos-issues#363]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

objects attached to driveboxes shift one stud away from the drivebox when loaded with the model builder

### How can we reproduce this bug?

attach anything to a drivebox in roblox studio and load it into the game

### Frequency

Always

**Comment by CL-2812** [comment]
See Issue https://github.com/Eggs-D-Studios/wos-issues/issues/362. Same bugged behaviour.
