### ISSUE TITLE
Add volume setting to Speaker & Boombox

### ISSUE THREAD

**Issue by TheRealSpriteMan1337** [Eggs-D-Studios/wos-issues#365]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

Improves audio significantly. You wouldn't need to re-upload stuff with volume changes, and we already have pitch on the Speakers anyways. I don't think this would be too hard to implement.

### What do you propose? What should change, or what should be added?

A setting for Speakers and Boomboxes that controls the audio's volume. Cap it, of course.

**Comment by khaopong23TH4** [comment]
Gotta give some ear damage to the opponents with this one🔥🗣🔥🔥
