### ISSUE TITLE
Part healths are inaccurate and scaling does not affect part health

### ISSUE THREAD

**Issue by dogranger1** [Eggs-D-Studios/wos-issues#369]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

Problem 1: Part health is inaccurate: several parts crafted out of stronger materials (such as iron) have very small health capacities. Examples of these are usually easy to find with crafted items, such as pumps, assemblers, chutes, wires, etc.  Usually, these parts have a health of 1.

Problem 2: Furthermore, the health of a part no longer scales with the size of the part. This was an important feature as smaller parts can be overused in structures to increase their durability

Fix 1: Calculate a mean durability out of all of the base ingredients of a crafted part. For example, assemblers require 2x Copper and 5x Iron. Iron's base durability is 12, whereas copper's base durability is 4. Calculate the mean durability: ( 2(4) + 5(12) )/ 7 ~~ 10 (rounded to the nearest int.). Of course, problems may arise as different base parts (ores) are different sizes and, hence, their "base durability's" will be different. When part durability's are proportional to their size, then the base durability should be equal to the durability of the part when the part's volume is 1.

Fix 2: Multiply the volume of the part by a constant to acquire the durability. Differ the constant depending on the strength of the part.

### How can we reproduce this bug?

Problem 1: Use F3 and hover your mouse over a part to see that the durability of the faulty part is equal to 1. To prove that this is not an error of the information's system, grab a gun and a bin of iron to see that the part will be destroyed in one hit (a default sized gun with ammunition of iron will deal 2 damage).

Problem 2: Use F3 and hover your mouse over a part, note the durability. Resize the part (assuming the part is malleable). Use F3 again to see that the part durability has not changed. You can use the same test described earlier to prove that this is not a fault of the information's system.

### Frequency

Always

**Comment by Hexcede** [comment]
> several parts crafted out of stronger materials (such as iron) have very small health capacities. Examples of these are usually easy to find with crafted items, such as pumps, assemblers, chutes, wires, etc. Usually, these parts have a health of

This is expected and was true in the past, it's not really a bug, they just don't have a durability defined, or have lower durabilities defined. Changing the durabilities of parts to be based on their ingredients isn't necessarily a good fix because it'd result in some parts with large crafting recipes becoming practically indestructible.

> Furthermore, the health of a part no longer scales with the size of the part. This was an important feature as smaller parts can be overused in structures to increase their durability

This was briefly a thing in unstable, but it was removed because it made some parts extremely overpowered. When I visit combat and balancing, which will be the next major update, I will come up with a good solution for this.

**Comment by dogranger1** [comment]
This has been made a feature and has been reworked.
