### ISSUE TITLE
Water effect does not appear in game

### ISSUE THREAD

**Issue by Pextri** [Eggs-D-Studios/wos-issues#37]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

When your camera is under the water, the water/blur and fog affect does not appear
![image](https://github.com/Eggs-D-Studios/wos-issues/assets/102265930/2c05c5af-aad0-4f4d-b437-f7fccb01b97e)

### How can we reproduce this bug?

Position your camera under the water

### Frequency

Always

**Comment by hail12pink** [comment]
id argue this as high-priority it's pretty gamebreaking

**Comment by dogranger1** [comment]
https://github.com/Eggs-D-Studios/wos-issues/issues/192 is a copy of this bug (and https://github.com/Eggs-D-Studios/wos-issues/issues/192 has been confirmed)

**Comment by dogranger1** [comment]
This has been fixed
