### ISSUE TITLE
Templates can be made out of false materials, some templates do not work and "Modify" can be used upon unusual parts

### ISSUE THREAD

**Issue by dogranger1** [Eggs-D-Studios/wos-issues#371]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

Problem 1: Templates that have not been replaced by the Modify section of the Hammer tool can be filled by non- malleable parts such as AlienCores, Obelisks, and various other parts.

Problem 2: Templates that have been replaced by the Modify section of the Hammer tool are still in-game and no parts will fill them. 

Problem 3: The Modify section of the Hammer tool can be used upon un-malleable/ unusual parts- such as Obelisks and AlienCores.

Fix 1: Create a list of parts that can fill these templates OR migrate these templates into the Modify section of the Hammer tool.

Fix 2: Remove the replaced templates.

Fix 3: Create a list of parts that the Modify section of the Hammer tool can modify so that certain parts (such as Obelisks and AlienCores) cannot be made into buttons or doors.

### How can we reproduce this bug?

Problem 1: Spawn/ craft a truss. Fill this truss with any un-malleable material (such as an AlienCore).

Problem 2: Spawn/ craft a replaced template (such as a hull) and attempt to fill it with a material (such as iron)

Problem 3: Spawn/ craft an unusual material (such as an obelisk) and use "Modify" to make it a door. Attach a button to the obelisk and press it. The obelisk should now be slightly transparent and CanCollide will be false.

### Frequency

Always

**Comment by Hexcede** [comment]
> Templates that have not been replaced by the Modify section of the Hammer tool can be filled by non- malleable parts such as AlienCores, Obelisks, and various other parts.

> The Modify section of the Hammer tool can be used upon un-malleable/ unusual parts- such as Obelisks and AlienCores.

This was now fixed for `Truss`. Other parts can still be shaped however I may change this in the future.

> Templates that have been replaced by the Modify section of the Hammer tool are still in-game and no parts will fill them.

They exist and spawn with the default components, but are uncraftable.
