### ISSUE TITLE
Railguns cannot fire when resized to be smaller than default size

### ISSUE THREAD

**Issue by CL-2812** [Eggs-D-Studios/wos-issues#382]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When resized below 6* 30* 6 (the default size), Railguns can be charged but not fired. They resume functionality once they are scaled back to 6* 30* 6 or above.

Note that this bug is not volumetric. If any one dimension of the Railgun is below the default value, it will not fire. For example, a 12* 45* 2 Railgun would not fire.

https://github.com/user-attachments/assets/1a32fe7d-5835-42f1-ac15-1c49957e2c6a

### How can we reproduce this bug?

1. Resize any one dimension of the Railgun to anything less than its default dimension.
2. Attach Rail Bin and Button to Railgun
3. Wait for Railgun to finish charging
4. Click the Button

### Frequency

Always

**Comment by Yeetano** [comment]
Apparently railguns only work if they’re at least 6 stud wide and tall and 30 studs long which I think is the default size

**Comment by Pextri** [comment]
@CL-2812 It literally says in both the discord bot and the in game help menu that there is a 6x6x30 requirement on the part -_-

![image](https://github.com/user-attachments/assets/38f25404-83ab-4dda-b904-cca93757c19a)
![image](https://github.com/user-attachments/assets/5575bd7d-3d25-4e0f-bad8-92eb87fc842d)

**Comment by CL-2812** [comment]
Huh, looks like it got updated. Issue closed.
