### ISSUE TITLE
Benign 'Duplication' Glitch with Wedges

### ISSUE THREAD

**Issue by Par1178** [Eggs-D-Studios/wos-issues#386]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I had two neon parts touching each other.  I wanted to turn them both into a wedge, so I put a wedge on them.  The wedge touched both of them, turning both of the neon parts into neon wedges using only a single wedge.  I managed to duplicate this glitch using two titanium and a wedge, and the bug occurred again.

### How can we reproduce this bug?

1. Have two parts that you can apply a template to.
2. Get a single wedge.
3. Make the wedge touch both of the parts at the same time.
4. Now you have two parts that are wedges using only one wedge template.

### Frequency

Always

**Comment by bladtax** [comment]
u can also put a wedge template onto a wedge template and make a wedge wedge name doesnt change but it stops being a template
