### ISSUE TITLE
Tractor beams with a power lever of zero do not consume power and cannot be turned off.

### ISSUE THREAD

**Issue by NobodyImportant64** [Eggs-D-Studios/wos-issues#39]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Tractor beams with a power lever of zero do not consume power and cannot be turned off. They behave exactly how zero speed thrusters in the main game work, where if they are set to a power level of 0 while powered, they will not turn off when power is removed and will stop consuming power.

### How can we reproduce this bug?

1) Spawn a tractor beam and a battery
2) Power up the tractor beam using the battery to some non zero power level
3) Set the tractor beam's power level to zero
4) Remove the battery

The beam will not shut down
![image](https://github.com/Eggs-D-Studios/wos-issues/assets/86064931/0789fb55-f646-48ff-a6e2-a91300a27b2f)

### Frequency

Always

**Comment by The4codeblocks** [comment]
pls no remove

**Comment by Hexcede** [comment]
Fix is pending, will be in the next unstable release

**Comment by hail12pink** [comment]
really annoying how this can't be autoclosed when pr merged because it's part of a different repo
