### ISSUE TITLE
Cloning bays work as a spawnpoint despite no power

### ISSUE THREAD

**Issue by Martynaspukis** [Eggs-D-Studios/wos-issues#394]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Despite the cloning bay having no power, you can still spawn there by clicking current location

### How can we reproduce this bug?

1. No power for cloning bay
2. No spawnpoint
3. Death
4. Spawn in Current location

### Frequency

Always

**Comment by Hexcede** [comment]
This is actually not a bug, was done that way intentionally, otherwise you have to put down a `SpawnPoint` as well, which only costs 2 iron and consumes no power.
