### ISSUE TITLE
be able to configure cjoint thickness

### ISSUE THREAD

**Issue by ikwsgbygikwsg** [Eggs-D-Studios/wos-issues#397]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

being able to configure cjoint thickness

### What do you propose? What should change, or what should be added?

purely a decorational feature 👍

**Comment by GTCEu** [comment]
make a limit so people wont abuse :+1:

**Comment by Hexcede** [comment]
Roblox doesn't provide a way to do this
