### ISSUE TITLE
Placing a tractor beam on a spinning motor causes extreme lag.

### ISSUE THREAD

**Issue by NobodyImportant64** [Eggs-D-Studios/wos-issues#40]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Placing a running tractor beam on a motor and spinning it will cause intense server lag. May be inconsistent because some of the time when trying this the beam simply does not turn on and lag is not notable.

### How can we reproduce this bug?

1) spawn a tractor beam, a motor, and two batteries
2) place the tractor beam on the motor and place one battery onto it to power it up
3) power the motor with the second battery

After this the tractor beam should either not properly project a beam, or cause ping to increase steadily with time causing a server crash within ~45 seconds. I am unable to replicate the bug further due to the fact that after trying to rejoin the game after the crash, the main menu is unable to load after two attempts stuck on "Retrieving planet data".

### Frequency

Only sometimes

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/66026ad3-2514-4e0e-8964-503d44dba8f0

`TractorBeam`s have now been optimised (as seen by the interacting with the `Iron` part having basically instant response times)
