### ISSUE TITLE
cryptic error when nonexistant function is encountered in microcontrollers

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#402]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

when microcontrollers encounter a nonexistant function they give this error
![Screenshot from 2024-09-13 22-50-30](https://github.com/user-attachments/assets/9975b2a7-ca24-47c3-95eb-318d84eb34d9)

### How can we reproduce this bug?

try running abuiuytuhat() in a microcontroller

### Frequency

Always

**Comment by Hexcede** [comment]
This error isn't cryptic, or a bug. `<compiled>` is your code. The rest of the stack trace is just the rest of the stack trace.
