### ISSUE TITLE
Bins not filling right

### ISSUE THREAD

**Issue by Yeetano** [Eggs-D-Studios/wos-issues#407]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Chute systems with multiple bins that hold the same item with an item source of the item dont fill right.

### How can we reproduce this bug?

1. Make a chute system
2. Place multiple bins configured to the same item
3. Place a devsource or whatever to supply like 10-100 of the item per tick
4. see that one of the bins fill (the last one to connect with the system) while the others don't

Bug may require large chute system with multiple bins of different bins of items as i noticed this starting to happen while building layer 2 of my storage.

### Frequency

Always

**Comment by mawesome4ever** [comment]
#366 
Cache issue, will be fixed

**Comment by Hexcede** [comment]
This is not a cache issue
