### ISSUE TITLE
Cant fly into planets from space.

### ISSUE THREAD

**Issue by vestifier** [Eggs-D-Studios/wos-issues#408]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Fly into planet with my ship, fall out of ship (my fault) and go back up but it is too high > Respawn at cloning bay, make new ship, warp back, fly into planet, ship too high in the sky, sends me back out. but and weird twist: I made two ships in total to go to planet > when I warp in, it sends me back out but with the OTHER ship I had previously?
Fly into planet > fall out of ship > respawn at cloning bay & make another ship > warp back > fly into planet > warp back out > suddenly in the first ship I made. 

### How can we reproduce this bug?

I think it might just be a me problem, but this happens consistently everytime.

### Frequency

Always

**Comment by voidstonism** [comment]
You can, you just have to fly into them on the bottom half of the planet, however its insanely annoying having to do so.

**Comment by vestifier** [comment]
> You can, you just have to fly into them on the bottom half of the planet, however its insanely annoying having to do so.

I tried flying in through the side and it also put me at the same spot.  I have not tried at the bottom tho.

**Comment by ARandomShark2** [comment]
can confirm this one

**Comment by VilgotanL** [comment]
you also spawn on the corner of the big cube of asteroids in space regions with asteroid chunks
