### ISSUE TITLE
Neither `Coordinate` objects nor it's metatable are frozen

### ISSUE THREAD

**Issue by LuaBloxor** [Eggs-D-Studios/wos-issues#409]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

Neither `Coordinate` objects nor it's metatable are frozen, this means i can modify these tables to affect things dependent on them.
Non-integer and out-of-bounds values can be assigned to these `Coordinate` objects (by setting `SolarCoordinates` and `UniverseCoordinates`), and `Teleporter` will teleport to them.
This screenshot in Staging is from using `Teleporter` to get to this coordinate (a `HyperDrive` that warped to this region is present).
![image](https://github.com/user-attachments/assets/5b12acee-729a-4325-917f-d9fbd7acea1f)

### How can we reproduce this bug?

1. Spawn a `Telescope`
2. On an attached `Microcontroller`, run:
```lua
local Telescope = GetPart("Telescope")
local CoordinateObject = Telescope.ViewCoordinates
print("is table frozen: ",table.isfrozen(CoordinateObject))
print("is metatable frozen: ",table.isfrozen(getmetatable(CoordinateObject)))
```
3. Observe both not being frozen

### Frequency

Always

**Comment by placeholder00** [comment]
Woah.
