### ISSUE TITLE
pumps go below -250 upon pumping water

### ISSUE THREAD

**Issue by orekay2** [Eggs-D-Studios/wos-issues#41]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

upon pumping water the pump and pumped water is below around -250

### How can we reproduce this bug?

pump water with pump

### Frequency

Always

**Comment by L5108313** [comment]
did you mean to say that water produced by pumps is created at absolute 0? because while im pretty sure thats what you meant, its not very clear.

**Comment by orekay2** [comment]
> did you mean to say that water produced by pumps is created at absolute 0? because while im pretty sure thats what you meant, its not very clear.

not sure, it could be, but don't bins/tanks get all their temperature from the resources inside, or is it a mix of the bin/tank temp and the resources

**Comment by orekay2** [comment]
accidently hit close

**Comment by L5108313** [comment]
ok i tested it and it seems that pumps produce water at absolute zero.

**Comment by Hexcede** [comment]
This is no longer applicable so it's fixed
