### ISSUE TITLE
Cant get stuff out of bins

### ISSUE THREAD

**Issue by Yeetano** [Eggs-D-Studios/wos-issues#410]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

Trusses cannot be ejected from bins easily due to the fact they eject horizontally, meaning they immediately return to the bin

### How can we reproduce this bug?

1. put truss in bin
2. click bin
3. truss no come out
4. make long dispenser
5. put on bin
6. truss come out horizontally

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/4cb1ac1d-68ef-45da-833c-2662387a887d

pretty sure this got fixed. pretty much every orientation is displayed and tested in the video, though the ones where the part re-enters the bin apply to pretty much every single part.

**Comment by hail12pink** [comment]
thanks dog rang er
