### ISSUE TITLE
Hammer Tool not welding parts correctly in Space

### ISSUE THREAD

**Issue by voidstonism** [Eggs-D-Studios/wos-issues#411]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I placed a bin on the floor of my station (in space) and when i bumped into it floated off as if it was wasn't welded to the floor

### How can we reproduce this bug?

Same as a above, make a station/ship (Y < 2000) and try placing a bin or parts on it, it also happens on ships in space as well requiring several tries to finally have it weld to a station or ship.

### Frequency

Most of the time

**Comment by ArvidSilverlock** [comment]
Also having this issue. Lost 2 ships to it, almost lost a third.

**Comment by hail12pink** [comment]
bug with roblox dragger, can't fix until custom dragger implemented

if you shake your drag all over the place it generally starts functioning again though

**Comment by dogranger1** [comment]
similar to https://github.com/Eggs-D-Studios/wos-issues/issues/368

**Comment by hail12pink** [comment]
i misread the bug report disregard what i said
