### ISSUE TITLE
stasis fields (the field itself) do not go away when the stasisfield part breaks

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#416]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When a stasisfield is broken, it leaves behind the field, which remains fully functional. 

### How can we reproduce this bug?

delete a stasisfield while it is activate

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/765a8882-19ef-4b71-bf55-0a63f3b02e81

this bug has been fixed

**Comment by hail12pink** [comment]
> 
> 
> https://github.com/user-attachments/assets/765a8882-19ef-4b71-bf55-0a63f3b02e81
> 
> 
> 
> this bug has been fixed 

the file is literally unmodified and i can't see where the bug could have occurred

**Comment by hail12pink** [comment]
needs proof if this still happens
