### ISSUE TITLE
Bug with either Storage or Part Welding 

### ISSUE THREAD

**Issue by Maggross** [Eggs-D-Studios/wos-issues#418]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Example 1. I have an assembler set to produce Thrusters. The assembler and the bin are both assigned. the assembler is powered (with a Wire leading to an antenna). All the ressources are present (connected via chutes). I have had the assembler set up on a straight line of chutes with all the other materials being connected via chute. When I add the Assembler and bin to the line of chutes and wires it dosn't assemble. When I remove it from the line and put on the material bins and power manually it suddenly starts working (mind that other assembly lines connected to the chutes dont have this issue and assemble just fine being connected to the chute)

Example 2. I have a Steam Turbine setup which I load in from the Studio. In testing the following thing happend: I loaded it the first time and attached an inf Coal bin and inf Water bin (Connected via chutes and everything assigned) it worked perfectly and gained power. Then I load it in the second time and nothing works anymore (Everything assigned and the bins attached)

I also loaded it into the real game and what happend was it produced power fine at first and then suddenly stopped putting steam into the container (I did nothing but hook up my ship via antenna to power it) I also still gained a surplus on ressources from the attached transporter into the bins but the boilers didn't use the ressources to create steam (might also be a bug with the boiler tbh)
I also tried the same as in Example 1 where I deleted the Tank and even rejoined nothing fixed it. 

### How can we reproduce this bug?

I have experianced the issues with assemblers when producing rubber and thrusters (keep in mind I use alot of assemblers connected to the same chute if that is helpfull in anyway)

for the steam turbine example I will leave the model code (Try loading in the Turbine 2 or more times it usually works the first time loading it in) the Water tank for the combustion turbine can be accessed by removing one of the back 3 boilers and setting it to water

### Frequency

Always

**Comment by hutek** [comment]
i have the assembler issue but not the reactor one

**Comment by Maggross** [comment]
Forgot to add the model code: {"m":null,"t":"buffer","zbase64":"KLUv/WDmKKVQAPpn7BY2EKjGOdAggiQJqviCdJKqHaIKgKo+wIyLIhwoOUkK+Ef0fj/Kz1SX0P+1b/+7WxePnev3JjIFPQFdAY0BWa/10u96rp8+2VO/+ctP/vHnJ/7w4Re6/+8V/A91zV5Z9H/h2+P/N+j2/+/Bf6v/DmfEtpdl2lzrl2vpG9+y39Zo/G55pxVS3/Yb9I76sizXdV3j+eNl+ds4fmerTqPxMttY9m9bofjx3x77r9PubP3n+Z3/t3Mbit/a/I1C8PwOx3+txe+on2ttow29W+J3fX/tpAy/4eV/vf2n6bvGv77/n77vIPzn//9btu7Gcu2JFmw29L++6fuf/qdve+sffz+balPrHL+NuZa+l//2DbXf8q2xhubaLXeelmvf6P5rKE7j+b/d5r9+3Mb7t2EzXLTQX/7p28bx/1/XnFKlSkXf9dPUfxv6b8O28d+u///x2y77r7f812n/Z2dnK1Sopf3bfk/f/3puVOlhHcLHStiZG0Te6/8J9k+08h/1AbLkK49hEAuLFp3HZZN6nIlVyq/XatdPaTM5fOULLzZbY+2rykIFr6oBBlsKHCC7psojF9EpLVKHBCZIiADhOZwdvA0YLCBqucUEL/aNrUy4heBAFEIErbmodBKHWbCzQNzhFw7bxibDCgBKYMBzriVkTaETBHyGe3ms8GM3V1xzcDKVSBhLNhaby+RxJg7hOPi8ElrVxrjDbw33APXHWDe2FXA1zGJcsdkQ3SpADIA4hIX9/4PB/5nm9O5/3N06W2fRVXS0ftY99AwdrNO92iX0Bn2ra/UBndmPvdiH/f1TH+oz/aR39Ile0Pd5PG/n4fyaP/NivstjeSnP5I08kNfxNV7Gv3jsp72JP3sPn+HBnn4K/+AVvIEX8FWf/eKjvVw3+yWP7PDnfd3Lj+gx/af363F3P/BBPeBv39R7+r7/+73ne73He7uv81hP93N/5c0+yjPf+EVe+c4PyvqrL9DUK5d6SY0SNddgN4aP67C33nEN9qA+8QXqeUIEGD87xZw2aapi8NvbYrpkqRIl+w9vyycpEqRHcWJ6fXt+jV5GixSNWf9G1IfHd+h1Y7P2oKFChAbNtf1f9Z7dVi84B9oB6I+fOLKbjuU8PKzgzGePnjzROiy3eOcux6sWLsR17IxCOnPkxHkWs8H5jZs2bKLzFaZclOCsRpsGDR1z7pXNlCEzJkoWM+uoYcB88VI1MudemcsWLVmiXlUKG+jQosxdQco5zZrUKRmVqGUlrkJlyrMrjiJjCYMzlB1PnDSJ07BE6RaVJEFyJCqdnUW4upBZsDB+EnmHCAnyTDJnJbJZjJ8/3n8/hgw4MRbYbIsr3BfW6nb96nIPHlYw3K5mXXj72BHHBStfOQeOGzY4DOHsK9OAm/EWnc5dzaMQ6RajDYZ05mJbc9GiK0sZnFmorbhWZymySZ2JQyFSRQoUJ6ob7iWaWyxBYoSIKDXJnJo1i1XKEC+ID2XVmcqcLqVHZxJ2dng5bNDwDHRaRbgZ/a3L+KirpHNS52QWFsLOHqOtw+gv/olkypGtuegtOpb5c498NLUV/drTProEKZcCRT/RTXzU7JFfpASJPqKL0BA/s5s92it/yc8v986fvtAdJughYhD9Qy/757bHD/h5HTj0DV3Dx8m/fbsHdIXNTnYldeEg1kbbVcRYx9DFepiZjKjOl7Xbvf6qq7TLqzMKhch+IbbQK3Svf/bV6cmdgnsVv/+PrdF2FbGmlmW7EaI/sU87l/v/fU0tex3rVZ3au7q0T/j7tI0AoT/oDj7Orw/TK3cGC7qCnuCv7xNfnzuCAz3aDfygDj+o33Y3q0CHdgKBPf7tm3oK6M7e/DhQ3V0qe7Ij+3r8gQ84Y3W5G3/Qg/q8Dn+f+//BoLJf7bDqxB7gB4k93mP6v8/rbo87/KZ+z40PdABxVRf24EddZR12x+/pt911j727V/0/1aP6ODeCjKgyAlUpHaoZSVKQwjAHcgyIo5yVEtoGEsDQeETRUAxDjGPGEGKIc0REoolGpKoDqMwCcTrpnfNYoB27SQdAgGIPwwdJLf1lJAjSPX9YcFE3jMUVZWYoHryrrnJEFSusgRbNIU5Q29/V/9YRBR8eLc4Dq3C6R4Qe/EG8B5Gt0YJpvMeyOpLPQcRGZdhoyvRcIKcYlVqruiyxfGo+NrE1bypzKiJ1DVzWyxmDuD7hjo68U+ywKYGPY1BDPYnDcrcQ5Hoerj4wMPyvsR5tkUrcSehAwD4e3NKNNI418EGCEr5+Ga+9nNiZeEGApvjc+m/3e5vnBvxLSLIFBNwZ+hOTKzEBdqFM5HVleRLjRzW6rpQcSjTaCN0N1BUQH8jYXHXIW4JdBklJIMjfiGUwwtdX0pa15FAFJqMMVE0PvpTi07EW7ETKuGMUwWZIUwWrcIyd/JYqWl9HZWRwxo+oQzF4oWssO/S2ilBEXZvbdbXoENGyrfKyGPOebr3Bx4mYl1rQN/KywK7oyFfTfjkG5hpxKZechsuSDqSpKMbApKVvauhBwm4iHweR2I4fl1KiZI425XElsT9VV27eBA5HgiW4xptqRVxhuL4LCPZjGqWXeE/7KH33sYtLpHVHkIDtZTdaszdq+ZaUQsx5MWMPJc0RVEIU4rz8i4QENpMl0RdOk5UHnUSsOGnNAmirQvi6sFlzeEbbwxIM+yLrMcIaTk3oPjCkFG8xLuWzL6kwCziBdE+Bn1Wrt12hUeiBDMO1W8tzwL2R0wNINX94OmYaw2hAcb+C1kIgg2AeUNtU40jkfsSzXBC8iz9FDT5x/JtD+QZs4+x7F8wLMr5G9+dV1G/rCWJSfAtWhhXceoIivgHuLd+/ao2VsBzrxRLxyosvtXNlGDAi+tG8Qz+wPkjyE+3r+BuN7cKfInr5ZW+Kh+sK5uyt5yezr2WSxaPsB2k+v6HHy5Q1Ka7pcY8ATVY8q68Svkd0SG+TliPEvVlaBwj7qxgH3GOjOFBodNOcIgatc2YY7FcuuXBJ2j9/ZIMlHVTLZzvoMlvOF2bF49IPGvh6ly9MFW/vSPpnUbFdrqNYynf64N21KLY1iCOYVt74ldP6yVYX4OxXNoobXChRSdDlXLp6YVazOb24cuanRg5+iOoFupR+2mIjjkb7LPKSRyiAdoHgWEVs8i/3PzBVD0afped3H69THGPmPTmNCMT8SgSyeiPM52/3OKSUKM8N4KJAfp1lS/FZ+pLyKoINGatk0A3kxnhbnw62BcgtQzpzvfW6xdnc3GivOlUZcwpbM6UNFRsRhCYD2NQ1unYX3qPM5u/TKVhGZXRQa45xzpNAeRJJnvXuQhRUv7wkSu0C8w6IvQpTKadkMJrkfubF1i2ZwTyOZKHozXf7QrkVckyUDI7mvHuqNjrXlOLm8j1L73MaOlTzZW7VpL3u79ZuX+NCHigVcAXXaqKIRcs2qnqMnh28WauuNg=="}

**Comment by HDMICIDE** [comment]
If your model was trying to be practical and not a piece of modern art it would be a lot easier to see what is going wrong, my best bet is you did not paste the model code directly from studio, when you save models from in game they tend to have issues with stuff randomly disconnecting and shifting apart

double check you even config the tanks since you need to do that now

i recommend you use something like this instead of what you built

{"m":null,"t":"buffer","zbase64":"KLUv/WCKDx0kAKZur0uwWHHG+cYOvQulB/42cLYQv//dK/wr/HFeUEZCsVHWc1B7m9WNq07UKJsx3aiXgVtb+8m6+ToWWgPh5VwFv00TkeZjfWxyhkiGTAGOAJMApAA8TDx7/34uQCj/fmp7c3C//hV41sqM2pxKtDnmeWZff9BEi/Sz/4Frl6+tDGwK/lzXlRLlyfpjgWYtG9od/9b9wCfB6yj9/rdyCqId+ypac/92+veW+bYWtbJ/1vzZ/WNzP/D176b557puEJCQ7medloJPX39vWpqVXqXJEhr2ivxTxUmNLFd/mSm/iOUPMQMEBHCdW8IAGxoc9KZCuSe00nNlkjMxogvAqNpmqclwk1pmv4R5u6DY13P0wvIIrZIpY0TxP9env/xlEiE9cNTwIbUgelGI8LBhW5DQAEEBGhhTd67SmRYsJrvNVhxNRVkpFDnq/6r457zyO6T/MdTlH4ov+r8Wr/rPlDPfdd3dj8/e/4by7/2vrYx/G6GyYN65Rm+vpkdYKPb1kmARGofEjav/v4if4e1aLZoo0TNCPGXmqYbIgfhw0swOISz7imoahofDjs4BBuoMxd3Elm1UlTaaDGsti4BFQ1eYloYwA4YLLwW0mZoTPvxRL8YNwTLRG9fglvfW9ArnRtWC9/bosQIFmwkNUqhMRVkwrQgQHjh40EpjLAbhAgUJIpSwtJU6EBp41bhaKWolngRKTYYxbLTrtQG32Ep26mC4FVXDxGSJEp3zhiJHvUICIEaRGJbjHlIS7417dOqIESJDYuZtJdPBcCuqJgiQHz58YOY5pjzCHTpyuG4znIqquRH+lmzoaBUNlW0n9vVO6D/GtoOKofTyeLDMYzU5QwaMF+ltloLJSbELnxWqxzsySpknTMZiV7TCjJ2sdUzhcEgoyEXBPHUpDTejqaQAoDCEkXY5Par4SeGD0m5jekIVgPao8TDpGBsRSZKCFDrwAiERGucSYDBJpKcgCIKQcoYIiBAyNCIigQgFhWoM4mZWfUXVxmvMRBrSc7NhGy9dR4iYQ2E8xUr3kivNmdKO2hJ+GKiT5CteFTJ8kWvGJFAZWOmHl5MwoT+nw7kcDbFYu0DI6nRFxuSJIvpp3ueqyeTSoftZujxMLV1+nWMvAeq9MQPBdsDhaLk3ogNZr19k1A/fnuHtlH8hvYSlLZOHp8/Z4NINENl/CePjWoVixEphfO5PQ8yEhBkAjZw5c+S6Mfywn7X4GKQ2D7JtiOkjQhVGIFaKqPqSYiD+sgivxImLQQyILYb+yMdMMO5mp9gGn61lAq0MgOsht40kblK5W46rV0niCA4xcPsytZ2GK9WIm0gtcrK5PbYoW4c8HQM03zcKoHUfbxeop0pUjh0RlgX7Bpg5ngYPzpxMgPXXPZUPTujMVefGGF0SXtWv0Rd2kG4exHWBN29IBWxBk1erciODMaLQqMH1ldS8qgDCuSimbLfj4Y6h3yVsDQfHcIT6KSB04mS2i78LQ2u1q+mTxatNjmARbVtdHXylUtLK9lJtkQu922lgUOpooU+9PrstS8+g1A=="}

**Comment by Maggross** [comment]
> If your model was trying to be practical and not a piece of modern art it would be a lot easier to see what is going wrong, my best bet is you did not paste the model code directly from studio, when you save models from in game they tend to have issues with stuff randomly disconnecting and shifting apart
> 
> double check you even config the tanks since you need to do that now
> 
> i recommend you use something like this instead of what you built
> 
> {"m":null,"t":"buffer","zbase64":"KLUv/WCKDx0kAKZur0uwWHHG+cYOvQulB/42cLYQv//dK/wr/HFeUEZCsVHWc1B7m9WNq07UKJsx3aiXgVtb+8m6+ToWWgPh5VwFv00TkeZjfWxyhkiGTAGOAJMApAA8TDx7/34uQCj/fmp7c3C//hV41sqM2pxKtDnmeWZff9BEi/Sz/4Frl6+tDGwK/lzXlRLlyfpjgWYtG9od/9b9wCfB6yj9/rdyCqId+ypac/92+veW+bYWtbJ/1vzZ/WNzP/D176b557puEJCQ7medloJPX39vWpqVXqXJEhr2ivxTxUmNLFd/mSm/iOUPMQMEBHCdW8IAGxoc9KZCuSe00nNlkjMxogvAqNpmqclwk1pmv4R5u6DY13P0wvIIrZIpY0TxP9env/xlEiE9cNTwIbUgelGI8LBhW5DQAEEBGhhTd67SmRYsJrvNVhxNRVkpFDnq/6r457zyO6T/MdTlH4ov+r8Wr/rPlDPfdd3dj8/e/4by7/2vrYx/G6GyYN65Rm+vpkdYKPb1kmARGofEjav/v4if4e1aLZoo0TNCPGXmqYbIgfhw0swOISz7imoahofDjs4BBuoMxd3Elm1UlTaaDGsti4BFQ1eYloYwA4YLLwW0mZoTPvxRL8YNwTLRG9fglvfW9ArnRtWC9/bosQIFmwkNUqhMRVkwrQgQHjh40EpjLAbhAgUJIpSwtJU6EBp41bhaKWolngRKTYYxbLTrtQG32Ep26mC4FVXDxGSJEp3zhiJHvUICIEaRGJbjHlIS7417dOqIESJDYuZtJdPBcCuqJgiQHz58YOY5pjzCHTpyuG4znIqquRH+lmzoaBUNlW0n9vVO6D/GtoOKofTyeLDMYzU5QwaMF+ltloLJSbELnxWqxzsySpknTMZiV7TCjJ2sdUzhcEgoyEXBPHUpDTejqaQAoDCEkXY5Par4SeGD0m5jekIVgPao8TDpGBsRSZKCFDrwAiERGucSYDBJpKcgCIKQcoYIiBAyNCIigQgFhWoM4mZWfUXVxmvMRBrSc7NhGy9dR4iYQ2E8xUr3kivNmdKO2hJ+GKiT5CteFTJ8kWvGJFAZWOmHl5MwoT+nw7kcDbFYu0DI6nRFxuSJIvpp3ueqyeTSoftZujxMLV1+nWMvAeq9MQPBdsDhaLk3ogNZr19k1A/fnuHtlH8hvYSlLZOHp8/Z4NINENl/CePjWoVixEphfO5PQ8yEhBkAjZw5c+S6Mfywn7X4GKQ2D7JtiOkjQhVGIFaKqPqSYiD+sgivxImLQQyILYb+yMdMMO5mp9gGn61lAq0MgOsht40kblK5W46rV0niCA4xcPsytZ2GK9WIm0gtcrK5PbYoW4c8HQM03zcKoHUfbxeop0pUjh0RlgX7Bpg5ngYPzpxMgPXXPZUPTujMVefGGF0SXtWv0Rd2kG4exHWBN29IBWxBk1erciODMaLQqMH1ldS8qgDCuSimbLfj4Y6h3yVsDQfHcIT6KSB04mS2i78LQ2u1q+mTxatNjmARbVtdHXylUtLK9lJtkQu922lgUOpooU+9PrstS8+g1A=="}

Appreciate the simplified version no idea what I was cooking. I also did load it from the studio and double check the presets of steam and water
btw thanks for helping my friend of the starter👍

**Comment by mawesome4ever** [comment]
Known cache issue, will be fixed.
