### ISSUE TITLE
some settings dont save

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#42]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Some settings, such as OST play frequency, Music volume, and Side menu size do not save.

### How can we reproduce this bug?

change settings and rejoin

### Frequency

Always

**Comment by Hexcede** [comment]
This should be resolved, let me know if it isn't
