### ISSUE TITLE
Power system randomly ceasing to function

### ISSUE THREAD

**Issue by HvyEarly** [Eggs-D-Studios/wos-issues#422]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I warped out of a planet and my air supply stopped working, and my battery was not getting or loosing any power even though I had many solar panels.  I tired to reconnect it but even when it was touching the battery it still was not working. Had to leave and rejoin several times before it worked again, and even then the majority of my switches stopped working.

### How can we reproduce this bug?

1. go into orbit of a planet
2. move electrical stations around to different wires
3. move and then put back switches.

### Frequency

I can't make it happen consistently

**Comment by mawesome4ever** [comment]
Wire cache issue, this is known and will be fixed.
