### ISSUE TITLE
cannot drag ship parts while on planet

### ISSUE THREAD

**Issue by HvyEarly** [Eggs-D-Studios/wos-issues#423]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

whenever I enter a planet with my ship, I loose the ability to drag all parts that were previously welded while I was in orbit. Any new blocks added to the grid are fine until I leave into orbit, and come back again. 

### How can we reproduce this bug?

1. leave planet
2. re-enter planet

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/5e157c70-87d4-46b4-9026-620ba91fa738

this bug has been fixed i think, though i wasn't active on the game when this report was posted and so i haven't encountered it.
