### ISSUE TITLE
"Failed request to send feedback"

### ISSUE THREAD

**Issue by LuaBloxor** [Eggs-D-Studios/wos-issues#433]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

It displays "Failed request to send feedback" every time i submit a feedback.
![image](https://github.com/user-attachments/assets/1adf0514-adbd-4799-a267-f9c3975ce8e4)

### How can we reproduce this bug?

Open the feedback menu in settings and send a message in it.

### Frequency

Always

**Comment by mawesome4ever** [comment]
Fix is already on it's way
