### ISSUE TITLE
Stuck on "waiting for roblox"

### ISSUE THREAD

**Issue by voidstonism** [Eggs-D-Studios/wos-issues#436]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

![image](https://github.com/user-attachments/assets/be8a84c6-508f-47e3-a3b9-18c4525e7f58)
It seems like its waiting on the skybox, and is not fully loading. if you wish i can dm you coordinates

### How can we reproduce this bug?

i do not know but might be a space server related issue

### Frequency

Always

**Comment by Hexcede** [comment]
> It seems like its waiting on the skybox, and is not fully loading. if you wish i can dm you coordinates

This is a symptom of the problem, not the cause

**Comment by Hexcede** [comment]
It is likely that you just need to be patient. During this step the entire region has already loaded and the only thing the game is doing is waiting for your player data to get fetched from Roblox. It is likely that you just need to wait longer.

**Comment by voidstonism** [comment]
ive waited around 5 min and several rejoins ima see if i can load into another region and maybe that might fix it

**Comment by voidstonism** [comment]
![image](https://github.com/user-attachments/assets/818c6602-1b83-420f-94be-6fdafcfc2679)
weird the location that this occur is also one of my cloning bay locations and this happened

**Comment by Hexcede** [comment]
> ![image](https://private-user-images.githubusercontent.com/133833783/370977307-818c6602-1b83-420f-94be-6fdafcfc2679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTc5MTIsIm5iZiI6MTcyNzc1NzYxMiwicGF0aCI6Ii8xMzM4MzM3ODMvMzcwOTc3MzA3LTgxOGM2NjAyLTFiODMtNDIwZi05NGJlLTZmZGFmY2ZjMjY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwNDQwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmU3N2FlYzM5ZDE3MzlhMDViYTFmZmEzYjRmNGVjNGI5ZTFjNTA1ZDdmMDk2ODZlYTVmZGJjNjZiODVjYzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PsuZn0VANBPDDYToD0QOXU4HcqccBK1qGXqA4Eswm-c) weird the location that this occur is also one of my cloning bay locations and this happened its the only one that seems to have this issue my other station does not have this issue what so ever

This icon means that the `CloningBay` doesn't have power
