### ISSUE TITLE
Resuming a yielded thread freezes the server under certain circumstances

### ISSUE THREAD

**Issue by LuaBloxor** [Eggs-D-Studios/wos-issues#438]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production), Development (Staging)

### What happened? What did you expect to happen?

Resuming a yielded thread from a thread spawned by it will freeze the server, in certain circumstances.

### How can we reproduce this bug?

Run this code on a `Microcontroller`:
```lua
task.wait(1)
for i = 1,5 do -- repeat attempt until it works
	print(`attempting... {i}`)
	task.wait()
	local co = coroutine.running()
	task.spawn(function()
		task.wait(2)
		coroutine.resume(co)
	end)
	coroutine.yield()
end
```
This code will keep attempting the bug until it freezes the server, since it sometimes fails.

### Frequency

Most of the time

**Comment by Hexcede** [comment]
this is wild
