### ISSUE TITLE
The Flipflop function does not work

### ISSUE THREAD

**Issue by anplayingelite** [Eggs-D-Studios/wos-issues#443]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When you switch a polysilicon to the "flipflop" polysiliconmode it does not give any signals to its switch near it. It is supposed to flip flop, aka turn on and off a switcth when it is connected to a button via triggerwire.

### How can we reproduce this bug?

1. Put a button, polysilicon and switch in that order
2. Click the button with the clickbutton/signal mode on emit
3. Switch the polysilicon to flipflop
4. The polysilicon does not signal and therefore does not change the switch to any mode.

### Frequency

Always

**Comment by Hexcede** [comment]
Can't reproduce
