### ISSUE TITLE
entering planets when not near planet / getting sent back to orbit after entering planet

### ISSUE THREAD

**Issue by ikwsgbygikwsg** [Eggs-D-Studios/wos-issues#444]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

entering a planet despite not being close to the planet itself and getting teleported back into orbit.
i also tried entering a planet the normal way but always get sent back to orbit.

### How can we reproduce this bug?

https://github.com/user-attachments/assets/3c6b6b3c-f4a7-473d-a40d-6f629058d158

### Frequency

Always

**Comment by anplayingelite** [comment]
Same thing happened to me, it only happens when you weld a part manually via hammer and put it on your ship,  I'm assuming the welded part went into an unknown far away offset position (still welded to your ship) and touched a trigger on the planet and up into the sky.

**Comment by ikwsgbygikwsg** [comment]
now that i think of it this is probably just be a sideffect of that manual placed partshift bug. couldve been that that partshifted parts did touch the planet and in planet the orbit plane

**Comment by NameTemplate** [comment]
mmm yes weld corruption
