### ISSUE TITLE
Cameras in AR

### ISSUE THREAD

**Issue by Messyman200** [Eggs-D-Studios/wos-issues#446]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

Camera UI elements could be used to make things like turrets and security cameras that can be viewed from anywhere in the region. They could also be used to have multiple cameras on one screen. Clicking to look through the camera could be replaced with a image button.

### What do you propose? What should change, or what should be added?

A screen element that connects to a camera ID, or an image button that can be set to a camera ID (ImageButton.Image = "CameraID:10")

**Comment by hail12pink** [comment]
there's a better suggestion that accomplishes this in here

**Comment by Hexcede** [comment]
> there's a better suggestion that accomplishes this in here

you should link to it

**Comment by hail12pink** [comment]
> > there's a better suggestion that accomplishes this in here
> 
> 
> 
> you should link to it

ok but i am evil,,,

**Comment by hail12pink** [comment]
#21
