### ISSUE TITLE
Lag Spike after loading large models

### ISSUE THREAD

**Issue by voidstonism** [Eggs-D-Studios/wos-issues#448]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Happens after loading high part count models (300+) Ping scales up to 1200+ then goes back to normal 
This could be related to #447 
![Screenshot 2024-09-28 075229](https://github.com/user-attachments/assets/3b35a0a9-bfdc-466b-835b-9713ff9b7dd5)
![Screenshot 2024-09-28 075415](https://github.com/user-attachments/assets/bef797fd-5330-475b-a5ea-04ea4dd99d7f)

(This also seems to be client sided lag as i was the only experiencing high ping)

### How can we reproduce this bug?

make a high part count model, then compile and load it in game.

### Frequency

Always

**Comment by Hexcede** [comment]
@voidstonism can you confirm this still happens, I pushed a change addressing this on the hour that you posted this

**Comment by voidstonism** [comment]
its fixed now ty
