### ISSUE TITLE
Tank-part ignoring set filter

### ISSUE THREAD

**Issue by Manufactoryman** [Eggs-D-Studios/wos-issues#449]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I was setting up gasoline production and for some reason the Tank set to Gasoline got filled with Petroleum.

### How can we reproduce this bug?

Place a refinery-setup (extractor set to oil, refienry, 2 tanks conected to refinery), set tanks to their respective filters and power everything 
![Screenshot (158)](https://github.com/user-attachments/assets/7968dbb2-5fa6-45d8-8512-b5ffbcc56a4c)

Additionally it seems lke the gasoline is not being created unless a bin that is already partially filled with gasoline is present
### Frequency

Most of the time

**Comment by NameTemplate** [comment]
can confirm, an empty tank with a resource configuration (e.g Water) can be filled by a resource that is not that set resource (e.g Steam).

**Comment by Hexcede** [comment]
Duplicate of #241 also don't post the same issue again with a different name just update the original issue next time if you find more information
