### ISSUE TITLE
Parts that despawn while being dragged create ghost parts.

### ISSUE THREAD

**Issue by 1-creare-1** [Eggs-D-Studios/wos-issues#45]
### Guidelines

- [x] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

If a part despawns while being dragged it will create a sort of ghost part in its place.

### How can we reproduce this bug?

1. Create a part that naturally despawns (like water)
2. Hold the part with the drag tool until the part despawns
3. Your now dragging a ghost part. You can move it around with the hammer (double click to start dragging it for some reason)

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/3e4f0f8e-406d-4380-b017-28da9998591c

fairly certain this issue has been resolved, as seen in the video above. The part gets deselected from the drag tool and cannot be reselected after it despawns.
