### ISSUE TITLE
Refinery ignoring filter-part

### ISSUE THREAD

**Issue by Manufactoryman** [Eggs-D-Studios/wos-issues#450]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

While making issue #449 I tried connecting a filter set to gasoline to the refinery and placing a tank (also set to gasoline) to the filter.
The tank set to gasoline got filled with petroleum through the filter set to gasoline.

### How can we reproduce this bug?

Same setup as for #449 just with filters introduced between the refinery and the tanks.
Works best when only 1 tank is present and the tank (and filter) is set to gasoline.

![Screenshot (160)](https://github.com/user-attachments/assets/a0b729f3-d98b-40fa-9ef0-f3f6b681638f)
![Screenshot (161)](https://github.com/user-attachments/assets/8ad43500-1de5-4ac2-8f26-d2d60a025b86)

### Frequency

Always

**Comment by Hexcede** [comment]
Duplicate of #241
