### ISSUE TITLE
hamer tool breaks while inside planet space mesh

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#451]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Staging)

### What happened? What did you expect to happen?

hammer tool cannot interact with anything it has welded together when inside of a planets mesh

### How can we reproduce this bug?

fly inside of a planet and weld two iron together

### Frequency

Always

**Comment by NameTemplate** [comment]
is it unable to weld the two iron together or is the two iron suddenly uninteractable after getting welded

**Comment by Hexcede** [comment]
This is a behaviour of the Roblox `Dragger` instance and is unfixable without a complete rewrite of the hammer code which is not something I am interested in doing atm but is planned
