### ISSUE TITLE
Focus Craft Search has a `v` in it when opened

### ISSUE THREAD

**Issue by sweetboss12512** [Eggs-D-Studios/wos-issues#454]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

title

### How can we reproduce this bug?

Open crafting with Focus Craft Search on

### Frequency

Always

**Comment by Hexcede** [comment]
This is a Roblox bug that has a fix being pushed soon, if it isn't already pushed
