### ISSUE TITLE
tempature bar not updating no matter what

### ISSUE THREAD

**Issue by GTCEu** [Eggs-D-Studios/wos-issues#455]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

i join game (spesificly a planet) and temp bar on top not work. (isnt updating) // simplest explenation i hope you cant fuck this up

I EXPECT THE BAR TO MOVE TO SHOW IF IM COLD OR HOT

### How can we reproduce this bug?

join wos. (planet.) // simplest explenation i hope you cant fuck this up

### Frequency

Always

**Comment by GTCEu** [comment]
this game acutally sucks bruh

**Comment by NameTemplate** [comment]
press f3 and check your body temperature. check if the body temperature changes but the white line in the temperature line doesnt move.

**Comment by NameTemplate** [comment]
btw you're sure that your temperature changed but the bar didnt move right?

**Comment by NameTemplate** [comment]
finally had some time to test, and it actually doesnt update
![image](https://github.com/user-attachments/assets/7e800442-5723-4c7f-bc18-485a8cc2c373)
![image](https://github.com/user-attachments/assets/fb8a7d1e-196f-4e43-8189-433760bce7ca)
![image](https://github.com/user-attachments/assets/5e4b905e-7fd5-4a13-9ee2-b017f39075fa)

**Comment by GTCEu** [comment]
> press f3 and check your body temperature. check if the body temperature changes but the white line in the temperature line doesnt move.

bro no shit what ive been doing

**Comment by Hexcede** [comment]
@GTCEu

**Comment by NameTemplate** [comment]
![image](https://github.com/user-attachments/assets/ff774fea-45ad-4fcc-98a9-def657d9983c)
appears to have been fixed
