### ISSUE TITLE
Allow arcontroller.CursorPressed:Connect() to detect right clicks as well as left clicks

### ISSUE THREAD

**Issue by wasteofsilliness** [Eggs-D-Studios/wos-issues#458]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A programming feature (e.g. APIs, tweaks, changes, etc)

### Why are you making your suggestion?

This would allow for dual mouse control for ships (e.g. steering with left click and aiming weapons with right click)
Also theres no way to detect right clicks

### What do you propose? What should change, or what should be added?

Allow arcontroller.CursorPressed:Connect() to detect right clicks and maybe middle clicks

**Comment by Hexcede** [comment]
This exists as `cursor.UserInput.Mouse`, can be detected via the `CursorMoved` event which fires every time the cursor updates. I will consider making this more intuitive at some point.
