### ISSUE TITLE
You cannot store powercells inside a bin by dropping them into the bin

### ISSUE THREAD

**Issue by Martynaspukis** [Eggs-D-Studios/wos-issues#459]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

You can't put a powercell inside a bin by dropping a powercell unwelded

### How can we reproduce this bug?

1. Drop Powercell into a bin unwelded
2. Fail

### Frequency

Always

**Comment by Hexcede** [comment]
This is actually a crude safety mechanism to prevent bins and containers full of stuff from being eaten, it will destroy the contents. I plan to change bins slightly as part of more upcoming QoL improvements.
