### ISSUE TITLE
Parts do not load when hinged ObjectDetectors are activated [Renamed]

### ISSUE THREAD

**Issue by liltinyten** [Eggs-D-Studios/wos-issues#46]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

When ObjectDetectors are turned on while on a hinge, any spawned part, whether crafted, spawned, or loaded in, does not load until the ObjectDetector is turned off.

### How can we reproduce this bug?

Place an ObjectDetector on a hinge, turn it on, and try spawning something. To see the parts that were supposed to be spawned, turn off the ObjectDetector.

### Frequency

Always

**Comment by Hexcede** [comment]
This almost certainly has no relationship to the `ObjectDetector` and I don't really understand exactly what you mean either. I would need a video of this, or a repro.

**Comment by liltinyten** [comment]
@Hexcede, I think I forgot to upload the video. When you power the object detector on a hinge, it causes parts to stop loading in. They all suddenly load in when you turn it off. 

Here is the video, I just reproduced it again:
https://streamable.com/mxojam
