### ISSUE TITLE
Heat Pumps Transfer heat at 0 TransferRate

### ISSUE THREAD

**Issue by liltinyten** [Eggs-D-Studios/wos-issues#47]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

I have a heater going to a heat pump that pumps into a pipe with a heat valve connected to a pipe that pumps into a diamond-insulated heat storage. Then, the transfer rate on the heater's pump is 0, but it still transfers heat.

https://github.com/Eggs-D-Studios/wos-issues/assets/29053643/795b462d-55cc-4022-a9c7-9b1a6b352d86

### How can we reproduce this bug?
Make the same setup.

### Frequency

Always

**Comment by The4codeblocks** [comment]
have you considered "preventing heatpumps from becoming perfect insulation"

**Comment by Hexcede** [comment]
> have you considered "preventing heatpumps from becoming perfect insulation"

I would probably close this for being invalid

**Comment by Hexcede** [comment]
This was resolved at some point, I forget when exactly
