### ISSUE TITLE
Apparels can no longer be configured to body parts

### ISSUE THREAD

**Issue by justthesam** [Eggs-D-Studios/wos-issues#489]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Apparels spawned or crafted do not have a configuration menu and apparels that were spawned in a model do not update their configurations and simply do not work

### How can we reproduce this bug?

1. Spawn an apparel (or load a model with it)
2. Attempt to configure it
3. (if model spawned) Attempt to wear it

### Frequency

Most of the time

**Comment by overdramaticpanromantic** [comment]
Also having this issue.

**Comment by Solrac2009** [comment]
Same
