### ISSUE TITLE
Apparel doesn't show a Config menu until the server is restarted - afterwards, Configs don't take effect when Apply is clicked

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Eggs-D-Studios/wos-issues#490]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Upon crafting an `Apparel`, I equipped the hammer tool and selected `Config`. I then clicked on the `Apparel` and attempted to configure its `BodyPart` to `Torso`. Upon clicking on the `Apparel`, the configuration menu didn't appear, similar to if you try to configure an object with no configurable fields (such as `Kiln` and `Wire`).

I assumed this was related to the `Polysilicon` typo bug, so once that was fixed, I left the server, waited for five minutes, and then rejoined to ensure the server had restarted. Upon loading into the game for the second time, the configuration menu for `Apparel` appeared properly. However, when I changed its `BodyPart` field to `Torso` and its `Transparency` to `0.5`, the `Apparel` didn't register the changes. Its size didn't change, nor did its transparency. Additionally, coming into contact with the `Apparel` no longer causes it to snap to the player.

I expected for the `Apparel` to change its size from 1x2x1 to 2x2x1, as `Apparel` usually resizes in such a manner when configured to `Torso`. Instead, the `Config` menu wouldn't appear, and upon server restart, `Config` changes weren't registered by the `Apparel`.

### How can we reproduce this bug?

1. Craft one `Apparel`.
2. Equip the `Hammer` tool and select `Config`.
3. Click on the `Apparel`.
4. Observe how nothing appears inside the `Apparel`'s `Config` menu.
5. Leave the game and wait for five to ten minutes, then rejoin.
6. Attempt to configure the same `Apparel` again.
7. Observe how the fields now correctly appear, but do not register changes when `Apply` is clicked.

### Frequency

Always

**Comment by overdramaticpanromantic** [comment]
Turns out my GitHub was being weird and didn't want me to see the other open issue about this. Consider this issue a supplementary issue to the other one with more detail.

**Comment by Solrac2009** [comment]
I have exactly this issue, but i also can't use the apparel once it has been welded to the ground, even when i unweld it
