### ISSUE TITLE
Reactors only output particle effects when at least one fuel bar is full

### ISSUE THREAD

**Issue by lilp123a** [Eggs-D-Studios/wos-issues#501]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

See title.

### How can we reproduce this bug?

1. Spawn in a Reactor
2. Fill it with Uranium - it will start producing steam particle effects
3. Raise the control rods
4. The temperature will rise, and the particle effects will go away. They don't return at any higher temperature.

### Frequency

Always

**Comment by placeholder00** [comment]
just to add on:
the particles are constantly emitted at 0f
and emits a few or one cycle when uranium is inserted
