### ISSUE TITLE
Mountains no longer always drop stone

### ISSUE THREAD

**Issue by ArvidSilverlock** [Eggs-D-Studios/wos-issues#507]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Mining mountain deposits no longer always drops stone, instead it seems to be treated as any other resource dropped by mountains.

### How can we reproduce this bug?

1. Mine stone
2. If it drops stone but not a secondary resource, keep mining till it breaks (even if it's not a bug and you have to keep mining for eternity)

### Frequency

Always

**Comment by Hexcede** [comment]
This is intended
