### ISSUE TITLE
Vehicle seats stop working when disabled and then re-enabled by a microcontroller

### ISSUE THREAD

**Issue by greg-the-greg** [Eggs-D-Studios/wos-issues#508]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

it just stops working.

### How can we reproduce this bug?

{"m":null,"t":"buffer","zbase64":"KLUv/WAGBG0SACacZEIwizYdYQqMh3ZKChjOg4KCgvrgwBOgR9xX/d13NxiSbdfPQDgufHd6gJm2/dIHwoDxyDbHdV2XIxq1Gfq7unYTu1NPAFQAUgCWioL/p+mvoJlW+FMSjJemCfwPp8r/i23bPJSUaB/9G5IPBm5DsnmEkXb927ZZNIY2MuLYthG/pn0z+sjo19ggcgkh/g4fOPzTL4n4L+IP0ELXmwEpAgNwe97F2V7uYq7buAwUEBDgqqrJdIuCqmgXRavipdf2PtRyYNX1btTukAdeokJRExQJ/0sX7Zm2pz2u++gOOHGxIoANiE/+yABBhcQVstqeFn+58bT9kWe1nAzos5ypEZmdafZMjy7KrHYY+QvZDmNvlzn7eWAy19beDAj5C9kKuEG2jJQywzoV0/sRtQaZYRgmY8qRm8LUzJDpUe56MJaKgv8lS0XBy4VkxQcOGmAUsJKmJMKdM50Q0hqUBQosElisA1TFglVWbctqO8oMk6+dmpmJUWId2NQ0iF4QdSeDOxT6MhlshzPI1ExRd6qlINDlYluo4SSFBgqqgjQFpTQGoKKyqnkRIDjNSjMjIiMFxRoD2IvESlzA9JSxmdJnp+A5U6BAm8wXlXBDc/h+ZYXf3SJ2a4OXFA5EGbIhfXcyk/Vfx5LSH8slKLCSsrvNa7ZbqUkCUYZelKYkwGKMZuS99AFFhx9iGYRgnymswHF1i0IoBFJfH0d9r7pZxlUDX3ZvVJw4PZZxNTvclOy9rA79RB/tfHQjKkdq9gT9rxIRK37l+OzoIboUBTU="}

### Frequency

Always

**Comment by Hexcede** [comment]
This happens regardless of whether or not the vehicle seat was configured by a microcontroller
