### ISSUE TITLE
Unstable random crashes

### ISSUE THREAD

**Issue by speeder5097** [Eggs-D-Studios/wos-issues#51]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

The game randomly crashes, and then takes a few minutes to retrieve planet info once you rejoin. No idea what causes it, but it happens consistently if you play for a decent amount of time.
It either gives this message:
![image](https://github.com/Eggs-D-Studios/wos-issues/assets/105261589/76c46a2e-7afe-46dd-a66e-9b02c40caab9)
or this one:
![image](https://github.com/Eggs-D-Studios/wos-issues/assets/105261589/6c25dbf0-f011-4911-9984-945808f7388c)
I've had both

### How can we reproduce this bug?

1. join unstable
2. wait
3. game should crash
4. rejoin and you will be stuck waiting for the game to collect planet information

### Frequency

Most of the time

**Comment by Hexcede** [comment]
There is a Roblox engine bug causing the servers to crash that I haven't been able to find the cause of or work around.

**Comment by sweetboss12512** [comment]
stuck on retrieving for like 5 minutes when this happens too
![image](https://github.com/Eggs-D-Studios/wos-issues/assets/101525599/a01050f9-83c9-4e16-bf43-2a6490c0b30c)

**Comment by Hexcede** [comment]
A workaround for this problem was implemented and functions
