### ISSUE TITLE
`spawn` with multiple objects to spawn doesn't work.

### ISSUE THREAD

**Issue by ArvidSilverlock** [Eggs-D-Studios/wos-issues#518]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

You cannot run `spawn` with multiple objects as the parameter separated by commas, even though the response text implies this should be a feature.

### How can we reproduce this bug?

1. Open F2 console.
2. Run a command such as `spawn Iron,Copper`
3. See response suggesting command ran successfully, but no objects spawn.

### Frequency

Always

**Comment by Hexcede** [comment]
You need to specify an amount (e.g. `2`). Pretty sure that I can't make this work because cmdr doesn't allow me to detect when an argument wasn't specified.
