### ISSUE TITLE
Sends you to 0,0,0,0 after rejoining while in space

### ISSUE THREAD

**Issue by speeder5097** [Eggs-D-Studios/wos-issues#52]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

When you go to space and rejoin, you will be sent to 0,0,0,0, and will not be able to get back to where you were before you rejoined.

![image](https://github.com/Eggs-D-Studios/wos-issues/assets/105261589/955e9b53-e608-41dc-985d-1c152b497b03)

### How can we reproduce this bug?

1. go to space
2. rejoin
3. respawn at the region you were at before
4. you spawn at 0,0,0,0, no matter where you were before

### Frequency

Always

**Comment by Hexcede** [comment]
You are not at 0,0,0,0. This is placeholder text that was showing up due to an error.
