### ISSUE TITLE
Expose more part events

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#520]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A programming feature (e.g. APIs, tweaks, changes, etc)

### Why are you making your suggestion?

Currently, it is impossible to detect when certain events occur without manually polling for them, which can be resource-intensive. For example, there is no way to determine when a Coupler couples/decouples. Having events available can enable builds that fluidly respond to their environments, such as a docking station that detects when a ship docks or undocks. At the moment, workarounds are required for this kind of functionality.

The PartData table lists a number of different events (e.g. `partdata.Parts.Coupler.Events` contains both a "Couple" event and a "Decouple" event) for each part, but these events are not exposed to user code.

### What do you propose? What should change, or what should be added?

This is a proposal to expose some of events listed in partdata to the user. The Coupler's events are just an example; I'm sure there's other objects with inaccessible events that would benefit from having those events made useable, like heartbeat events for parts that update such as the ObjectDetector or the LightBridge.

I am aware that this is a rather large proposal compared to a simple "add X", but is one that IMO needs to be addressed at some point and I haven't seen any other issues tracking it.

**Comment by placeholder00** [comment]
🙏

**Comment by hail12pink** [comment]
coupler is the only one that makes sense here but yeah

**Comment by Hexcede** [comment]
The heartbeat stuff you can already handle by just using `task.wait()` in a loop
