### ISSUE TITLE
MBTools: Instrument inserts with NumberValue "Type" configurable, instead of StringValue

### ISSUE THREAD

**Issue by lilp123a** [Eggs-D-Studios/wos-issues#521]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Instruments inserted with MBTools are given a "Type" NumberValue, instead of it being a StringValue.

### How can we reproduce this bug?

1. Insert an Instrument using MBTools
2. Profit?

### Frequency

Always

**Comment by Hexcede** [comment]
@lilp123a Update your MBTools version
