### ISSUE TITLE
extractors not working

### ISSUE THREAD

**Issue by oskarvello** [Eggs-D-Studios/wos-issues#523]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

when powering extractor it did not output the resorces as it was supposte do i set the extractor on the mountain wall and set it do extract Sulfur and yes i rembered do put it case sensitive and it still did not work tried using it on other resorce nodes like copper iron and etc and still no output i was powering the extractor with batterys and i did place the extractor the correct way the black side exposed do air and the other side exposed do the resorce terrain i tryed it on diffrent planets and still didnt work

### How can we reproduce this bug?

power extractor set do the resorce terrain with the correct selected type

### Frequency

Always

**Comment by NameTemplate** [comment]
you need to put a bin on it. extractors no longer drop the resources when there is no b8n

**Comment by Hexcede** [comment]
What @NameTemplate said is correct @oskarvello
