### ISSUE TITLE
MBTools: Inserted Bins/Tanks do not have "Resource" configurable

### ISSUE THREAD

**Issue by lilp123a** [Eggs-D-Studios/wos-issues#524]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Title.

### How can we reproduce this bug?

Title.

### Frequency

Always

**Comment by Hexcede** [comment]
@lilp123a Update MBTools.
