### ISSUE TITLE
getting killed while wearing an apparel causes that apparel to inflict instant cardiac arrest on anyone else who puts it on

### ISSUE THREAD

**Issue by imawxome** [Eggs-D-Studios/wos-issues#531]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

After making a makeshift jetpack with an apparel on my torso, I (predicably) fell three thousand feet and died. after this, the apparel inflicted me with "instant death syndrome" anytime I tried to put it on again

### How can we reproduce this bug?

1. wear apparel
2. die
3. apparel is now haunted by your ghost, will kill you the moment you touch it

### Frequency

Always

**Comment by NameTemplate** [comment]
iirc only when the apparel is equipped to torso, and applies to prosthetic as well

**Comment by placeholder00** [comment]
this bug has been here at minimum since i started playing

would be nice to have this fixed but for now i recommend using a head apparel as a workaround

**Comment by LuaBloxor** [comment]
replicated this bug with a simple apparel script
https://www.roblox.com/games/14326579832/weld-reset-bug

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/4c1d4146-cff9-42e1-ad41-3cec14adce18

pretty sure its fixed, even tried with fall damage taken
