### ISSUE TITLE
`Artillery` projectile despawning after reaching a certain distance from where they were fired

### ISSUE THREAD

**Issue by placeholder00** [Eggs-D-Studios/wos-issues#533]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

`Artillery` projectile freezes its expected trajectory after reaching a certain distance from where they were fired and then become uncollidable and fall downwards.

what i expected to happen is that i get absolutely decimated by the 10 artillery turrets targeting me, while im standing completely still.

*Edit:* ARTILLERY COUNTS AS ENERGY DAMAGE, RAHHHHHHHH

### How can we reproduce this bug?

this is most noticeable with max length artillery, as the speed causes it to travel quite alot of distance

1. you can attach this max length artillery on an average gyro turret setup and set it to target yourself (try to place the artillery's center of gravity inside the gyro so that its less wobbly
2. move about 5k studs away
3. fire the artillery
4. watch the projectile fall down through the baseplate

the distance where the despawn happens seems to be random but i can only assume that this is because the frequency of checks is inconsistent?

artillery damage is blocked by ENERGY SHIELDS, AAAAAAAAAAAA.

### Frequency

Always

**Comment by Hexcede** [comment]
This is not a bug, artillery shells have a maximum range of `4000` studs.

**Comment by placeholder00** [comment]
boowomp...
