### ISSUE TITLE
Creating a GUI frame element with Visible data being set to false doesn't make it invisible

### ISSUE THREAD

**Issue by Martynaspukis** [Eggs-D-Studios/wos-issues#536]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

reactorfuelframe = screen:CreateElement("Frame", {Position = UDim2.fromScale(0,0); Visible = False; AnchorPoint = Vector2.new(0,0); Size = UDim2.fromScale(1,1); BackgroundTransparency = 0; BackgroundColor3 = Color3.fromRGB(192,192,192);}

This creates a frame that is visible, despite second data being Visible = false. This should make the frame invisible, but its still visible. By using Frame.Visible = false in the next line, it makes it insivible, so it is only in creating the GUI element.

### How can we reproduce this bug?

1. Create a GUI frame element with "Visible = false" being a part of its data
2. Run code

### Frequency

Always

**Comment by Hexcede** [comment]
Your reproduction capitalizes `False`. It should be `false` (case sensitive).

**Comment by Hexcede** [comment]
I'm assuming this is invalid and can't repro it, so I'm gonna mark it invalid for now.
