### ISSUE TITLE
Object Detector Lag

### ISSUE THREAD

**Issue by minimic2002** [Eggs-D-Studios/wos-issues#541]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

As i predicted multiple object detectors can lag the game, what a great idea to fire tons of rays a second!

### How can we reproduce this bug?

play the game with any of the trash players trying to make lidar or their own version of a camera, its tragic

### Frequency

Always

**Comment by justthesam** [comment]
mmm yes i wonder who that person is (orange)

**Comment by minimic2002** [comment]
true but he isnt even using that many, its only like 20
i did say it would be best to have to trigger or use a method to use objectdetectors before this just shows it more

**Comment by Hexcede** [comment]
Raycasting is not actually all that expensive, nor is this really a bug, this is just a performance issue. There are a lot of parts in the game that are immensely laggy in quantities more than a handful. Performance issues like these are something that I'm not focused on solving right now, I solved a lot of performance issues prior to wipe and while I am concerned about abuse and lag machines and stuff it's not a huge priority atm.

**Comment by Hexcede** [comment]
It's substantially more likely that the lag is from the game's ray code in general rather than the raycasting. It's poorly optimized, especially in the case of `ObjectDetector` which casts a new beam every single frame, which destroys and recreates the beam part, etc.
