### ISSUE TITLE
every time i press v to open craftng its already searching for v

### ISSUE THREAD

**Issue by minimic2002** [Eggs-D-Studios/wos-issues#542]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

when you press v it also enters v into the search so u gotta stop what ur doing and press backspace, how inconvient!

### How can we reproduce this bug?

aaaa

### Frequency

Always

**Comment by Hexcede** [comment]
This is actually a Roblox bug, not a WoS one.

![image](https://github.com/user-attachments/assets/937d3988-d64b-40fa-99d7-c6f3fe1ab63a)
https://create.roblox.com/docs/release-notes/release-notes-646
