### ISSUE TITLE
More Event Improvments

### ISSUE THREAD

**Issue by minimic2002** [Eggs-D-Studios/wos-issues#545]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Development (Staging)

### Topic

A programming feature (e.g. APIs, tweaks, changes, etc)

### Why are you making your suggestion?

while some events were added theres still alot missing in places, like any part that has anything to do with triggers should have .Triggered
.Touched should pass on the part it hit (TouchSensor)
modem should use a event for recieving messages

### What do you propose? What should change, or what should be added?

its needed

**Comment by Hexcede** [comment]
> like any part that has anything to do with triggers should have .Triggered

Not all parts actually respond to trigger signals so this isn't generally possible

`.Touched` passing a reference to the part is fine by me though
