### ISSUE TITLE
Cannot toggle shiftlock in game

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#552]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Shift lock cannot be toggled in game from the roblox settings menu. It can however be toggled in the lobby place.

### How can we reproduce this bug?

look at settings and notice the lack of shiftlock setting

### Frequency

Always

**Comment by Hexcede** [comment]
This isn't a bug, shift lock is disabled because sprinting uses shift @L5108313
