### ISSUE TITLE
wierd Size-edit bug ( glitch )

### ISSUE THREAD

**Issue by Mohammed50km** [Eggs-D-Studios/wos-issues#553]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

So evreytime i use the resize tool, the object that im resizing falls of or does wierd stuff like shaking

### How can we reproduce this bug?

 1. Warp to space.
 2. Warp back to the planet.
 3. Warp to space again and repeat until something happens.
 4. Sometimes, your ship will disappear or be duplicated.

 1. Set up a `Filter` for `Sand` that's attached to a `Kiln` and a `Sand` bin.
 2. Turn on the `Kiln` and observe that it can't find the `Sand`.

### Frequency

Always

**Comment by Mohammed50km** [comment]
Uploading Roblox VR 2024.11.07 - 21.01.28.03.mp4…

**Comment by dogranger1** [comment]
Note: the repro steps have not been changed 💀 

https://github.com/user-attachments/assets/7443f733-bb64-43d0-9714-507379a78b9f

This bug used to happen when a part was selected as the welds would break, but I'm pretty sure its fixed now.
