### ISSUE TITLE
Gyro TrigMin is broken.

### ISSUE THREAD

**Issue by liltinyten** [Eggs-D-Studios/wos-issues#554]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

It's similar to issue #540.

It doesn't care about what's IN the range of TrigMin and TrigMax if anything is below the TrigMin it will stop triggering.
So if there IS something in that range, it will NOT be detected.

https://github.com/user-attachments/assets/ec7024af-e2f9-4322-a0f5-8a9a392d650d

The red Titanium starts below TrigMin and when I move it out of TrigMin it starts triggering because the second Titanium is closest and is in the TrigMax
But when I place the red Titainium back where it was the triggers stop. (I selected it again to unweld). 

### How can we reproduce this bug?

1. Spawn a gyro.
2. Add something to test if it triggers.
3. Set it to target something with a TrigMin.
4. Place something beyond the TrigMin.
5. Watch it trigger.
6. Now place something inside the TrigMin.
7. Watch it stop triggering.

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/2fbea32a-1118-493d-8583-8a3f227ab90c

leave no gap between "trigmin" and the value

**Comment by liltinyten** [comment]
Did you not understand what I did? I had **TWO** parts. A TrigMin and a TrigMax. If you understood the post properly, you would see that it would stop triggering when an object was below the TrigMin even when there was a part above the TrigMin.

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/1c9e3702-4153-4f59-99ba-84c70ac698aa

sorry for the mistake earlier, but this "bug" occurs because the gyro tracks the closest object. If you want something like this use a scanner and a microcontroller.

**Comment by liltinyten** [comment]
I already found a better solution. I just used Min and Max instead of TrigMin and TrigMax.

**Comment by dogranger1** [comment]
thats pretty cool, but surely there would be errors occuring because the gyro can only track one part at a time (i.e. there is a maximum amount of parts that the tracker can track)
