### ISSUE TITLE
Add Microcontroller:Start()

### ISSUE THREAD

**Issue by liltinyten** [Eggs-D-Studios/wos-issues#557]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A programming feature (e.g. APIs, tweaks, changes, etc)

### Why are you making your suggestion?

You can shutdown other microcontrollers by calling `Microcontroller:Shutdown()` on them. Why not have a way to start a microcontroller by calling `Microcontroller:Start()`?

### What do you propose? What should change, or what should be added?

Just add `Microcontroller:Start()`.

**Comment by liltinyten** [comment]
I guess this was changed at some point, but it's added.

**Comment by hail12pink** [comment]
yeah it was he forgor to close
