### ISSUE TITLE
Sorters eats items and spits out only one output

### ISSUE THREAD

**Issue by GooberGoonie** [Eggs-D-Studios/wos-issues#558]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

This bug has been reported but was put as closed but it's happening to me, occasionally a sorter will take for example 50 energy bombs and 1000 rubber, into a 10x10x10 bin configured to energy bombs with the sorter settings set to 'Solid' and 'inf'. the energy bombs will be eaten by the sorter and the energybomb bin will fill with the 1000 rubber.

### How can we reproduce this bug?

repeat what was done in the first part

### Frequency

Always

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/d83d8053-6ae6-4a34-81bc-1865cd33a4ae

Note: this is randomised, so if the bin is set to "Rubber" it will fill up with either Rubber or EnergyBomb s. The same does not  apply if it is set to "EnergyBomb". 

https://github.com/user-attachments/assets/478f23d2-b375-4f45-b1d0-58076b5b9169

This is a demonstration of where the Rate is not "inf". This does not work with EnergyBomb s when the sorter's Resource is set to "Solid" though.
