### ISSUE TITLE
Cant remove modification

### ISSUE THREAD

**Issue by Mohammed50km** [Eggs-D-Studios/wos-issues#559]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I wanted to remove a door modification after adding it to iron, after trying over and over again it seems that removig the "door" modification is not possible.

i tried to rejoin, but the issue waws still there.
![2024-11-10_111506](https://github.com/user-attachments/assets/3b382757-dda5-421f-bde5-d33acf5bd85e)

### How can we reproduce this bug?

its constant

### Frequency

Always

**Comment by NameTemplate** [comment]
did you click apply? (i know this is obvious but im gonna ask anyways)

**Comment by dogranger1** [comment]
https://github.com/user-attachments/assets/51cd54e9-b2c8-471f-a123-d0bbee8e06a0
