### ISSUE TITLE
Game doesn't work when loading in via Sober

### ISSUE THREAD

**Issue by braainsiogame** [Eggs-D-Studios/wos-issues#563]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

(Client: Sober 0.0.0-78a4e30)

Joined the game and went into testing zone. 
The text on the buttons doesn't disappear, clicking on the buttons doesn't do anything. I can't open settings, I can't even run. Hovering over a part doesn't display anything.

![image](https://github.com/user-attachments/assets/f8203544-f15a-486d-9925-aa241a1b6198)

### How can we reproduce this bug?

1. join a world
2. it just does that

### Frequency

Always

**Comment by Hexcede** [comment]
This is a sober issue
