### ISSUE TITLE
Coupler connections need updating for it to realize it is connected

### ISSUE THREAD

**Issue by NameTemplate** [Eggs-D-Studios/wos-issues#564]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

The coupler itself connects fine. Wires/pipes/chutes that touch due to a coupler coupling are supposed to create temporary welds that transfers their respective resources. This does happen, however it needs the connections to update (e.g. by welding something onto the wire/pipe/chute) for the transfer thingy to also update.

### How can we reproduce this bug?

1. Have two couplers with wires/pipes/chutes that would connect when the couplers couples
![image](https://github.com/user-attachments/assets/be1ba1c3-04bd-4713-b1af-455cfeee175d)
![image](https://github.com/user-attachments/assets/79856546-2043-43fe-aa31-81253fe30e50)
2. Couple the couplers
3. Witness that the wire/pipe/chute connection doesnt connect
4. Weld something onto one of the wire/pipe/chute
5. See it work?
6. Uncouple the couplers
7. See the wire/pipe/chute somehow still being connected

### Frequency

Always

**Comment by RiskoZoSlovenska** [comment]
FYI, Ethernet queries (e.g. `GetParts()`) made from a handler of the `Couple` event do not see the newly-attached components. Adding a `task.wait()` to the top of the event handler makes it work. Not sure if that's intended.
