### ISSUE TITLE
Polysilicones broke again

### ISSUE THREAD

**Issue by Metirolous** [Eggs-D-Studios/wos-issues#567]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Polysilicones have been having issues with loading from Roblox Studio AND also have had issues with translating trigger signals to reactors AFAIK. They don't affect the reactor rod levels when you trigger them via port, or by clickbutton component, and can only work if you put a regular button on it.

### How can we reproduce this bug?

1. Make code which triggers polysilicone
2. Weld it onto reactors and switch around their configurations to change rods
3. (Studio) Use both regular MBtools and MBEE, both their parts and compilers, and see that no matter what activation they have it will always be set to `activate`
4. Either temperature sensors don't work or reactors are showing inaccurate temp readings which is causing them to not send trigger signals. (side note) Reactors also show wrong numbers, they say they're at 500C but on the screen they are 800

### Frequency

Always

**Comment by placeholder00** [comment]
Happens to other parts too, or at least is related to that problem

I really thought lua has already reported this already since its been bothering people for more than a week now

**Comment by placeholder00** [comment]
Something to do with or at least related to welds not being recognized by code*

**Comment by dogranger1** [comment]
pretty sure that this report is wrong, just tested a reactor loaded from roblox studio with some simple reactor code and it works just fine. In model builder, Polysilicon modes range from 0 - 2, where 0 = activate, 1 = deactivate and 2 = flipflop (this is probably why they keep getting set to activate).
However, Polysilicon with a ClickButton component installed will not trigger itself.
![image](https://github.com/user-attachments/assets/5adb9b4a-3e47-4b82-bef1-b59a49fcd5e0)

Reactor model code:
`{"m":null,"t":"buffer","zbase64":"KLUv/WC1BBUSACZZXEQgj5oOAGyBIAEDANcaEAA2QJCCAYYASnxn40ZTXYFtm9nBl0ZqtxRjpbvH+s0Oc4z+qcdWoGUnOrDamu0lRm50EyEyBUMAQgBTAH/2X0rv/0T+ryXzMu+XnBUfRrT/H4ufgKiZx/k/locyT7J4X4j/+y85/5zzoZD8nnm/BqKyorVQWdHinK/+Sft7xB/WpZfAlNP6VQZGlMc3V2o99A8v0bqYpl+TtTz6rQgOEBDIVB8b7IJU/6+mf4NmCuqfktr6pSnq/z09/ieZc3bYEPncCe1k22ErImvAGCxQkACD0eVACYeM76cvoEfG90NxDHQU0EiNTccBsaH0W9D1YFJqZ1GcsHhDYwigAmh0t27chpLC3c/FsaEBAK9oumAoTIaEAVj/744kFnQ7TUlp2drRjLKVkKgb11FBPS11l4KaMOk6ZEyzSccLFShYGJmQwZbjLs7drRfXzYPJgEFEAowuECiPGPIAhONjc11QyjSQbHSoAa12qmQkKUghrQHQAimiqgMRQEQItUBEhEpRaTLMAUrh5KvjVUceE+G63jiMcqk9HmF0vPCxsunDPp8oVjF8L+HJoDBApdgIZtTdSn5uBoayimZWRf+KET01PkoFvBJ8Ktfbdmf+gfEMAABkhy+XxE1cmy1t2w7nz8oQzxay0/ntrYZkBXiWZFrQz81XkZ+UO1luabYDetbUSqLK2hxEyomoUV8wcaybIRUp8u7GydmIVsteb6xo/fwwlkYF8pSRTzEnuZABmtAgKFQB"}`

Reactor microcontroller code:
```
      local reactor = GetPartFromPort(2, "Reactor")
      local polysilicon = GetPartFromPort(1, "Polysilicon")
      
      while task.wait(0.1) do
          local temperature = reactor:GetTemp()
          if temperature > 30 then
              polysilicon:Configure({PolysiliconMode = 0})
              polysilicon:Trigger()
          elseif temperature < 20 then
              polysilicon:Configure({PolysiliconMode = 1})
              polysilicon:Trigger()
          end
      end
```
