### ISSUE TITLE
RealPostRequest hangs

### ISSUE THREAD

**Issue by Apethesis** [Eggs-D-Studios/wos-issues#57]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Stable)

### What happened? What did you expect to happen?

Trying to make a post request to a server i have just makes it hang and not do anything, using any other  program to make the same post request doesnt hang and works flawlessly.

### How can we reproduce this bug?

 1. Set up a microcontroller connected to a modem
 2. Put in some specific code (dm me @cepmowoc, you need an access token)
 3. Try activating the microcontroller
 4. Profit(?)

### Frequency

Always

**Comment by 0mori1** [comment]
cat with raised eyebrow

**Comment by NameTemplate** [comment]
why not put the code here, but not have the access token in it
it could be a mistake in the code

**Comment by Hexcede** [comment]
This is probably already solved in unstable, I would check to make sure.

**Comment by dogranger1** [comment]
`RealPostRequest` is deprecated and has been replaced with `PostAsync` . `PostAsync` works just fine (demonstration of `BlackBox` data being sent to a discord bot is shown below)

![image](https://github.com/user-attachments/assets/93dbe5f1-a67a-477a-876a-b2f760757259)
