### ISSUE TITLE
Client script is broken

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#575]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Whenever I join a testing place, sprint, hovering and respawning are entirely broken and the following error can be found in the dev console:

```
TextChatService.OnChatWindowAdded is not enabled.
    Stack Begin
    Script 'ReplicatedStorage.Client.ClientModules.ChatHelper', Line 9
    Stack End
Requested module experienced an error while loading
    Stack Begin
    Script 'ReplicatedStorage.Client', Line 23
    Stack End
Requested module experienced an error while loading
    Stack Begin
    Script 'ReplicatedStorage.Client.PlayerClient', Line 16
    Stack End
ReplicatedStorage.Client.ClientModules.ClassesClient:288: attempt to index number with 'Parent'
    Stack Begin
    Script 'ReplicatedStorage.Client.ClientModules.ClassesClient', Line 288
    Stack End
```

I am running Roblox on Linux via Sober; I'm guessing that may be what's causing this bug to occur.

### How can we reproduce this bug?

Join the game using Sober.

### Frequency

Always

**Comment by dogranger1** [comment]
copy of https://github.com/Eggs-D-Studios/wos-issues/issues/566 ?

**Comment by Hexcede** [comment]
This is an issue with Sober. Sober is currently 6+ versions out of date and doesn't have the new chat APIs as a result. Not planning to fix/workaround this as a result.
