### ISSUE TITLE
`NuclearWaste` duplication when reflecting reactor's `TriggerWhenEmpty` signal into `FlipFlop`

### ISSUE THREAD

**Issue by LuaBloxor** [Eggs-D-Studios/wos-issues#576]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

`TriggerWhenEmpty` emits a signal when rods are depleted, if converted into a `FlipFlop` signal consumed by the `Reactor`, it will dispense waste but doesn't empty the rods.
![image](https://github.com/user-attachments/assets/ee1ce737-0a32-4df6-a237-fbff8aad4487)

### How can we reproduce this bug?

1. Place `FlipFlop` polysilicon and a `RemoteControl` like this:
![image](https://github.com/user-attachments/assets/7f4f8076-3374-4619-8cce-49382402f05a)
2. Spawn this reactor with a command: `s reactor 1 0 # {"TriggerWhenEmpty":true} {"ControlRods":0.5, "Fuel":[0.005,0.005,0.005,0.005], "ReactorTemperature":950}`
3. Place the reactor on the polysilicon and wait for it to run out

### Frequency

Always

**Comment by Hexcede** [comment]
This is not a bug, up to 4 `NuclearWaste` can be extracted total.

**Comment by Hexcede** [comment]
Nevermind I have stupid
