### ISSUE TITLE
`Muffler` component

### ISSUE THREAD

**Issue by hail12pink** [Eggs-D-Studios/wos-issues#579]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

cool use of components and lets you selectively make something quieter. better than just applying it to all machine sounds within a 100 stud radius.

### What do you propose? What should change, or what should be added?

add `Muffler` component that reduces sounds created by a part by a percentage (stacks additively, for example like, `-15%`, `-30%`, `-45%`, etc.)

probably should have a limit so you can't completely mute weapons or anything.

**Comment by hail12pink** [comment]
this is assuming multiple components of the same type can be installed onto the same part, i guess they probably can't but it shouldn't be that complex and i think future part modifications like this would work neatly and be very intuitive with the component system.

**Comment by hail12pink** [comment]
> this is assuming multiple components of the same type can be installed onto the same part, i guess they probably can't but it shouldn't be that complex and i think future part modifications like this would work neatly and be very intuitive with the component system.

it's kind of similar to like mekanism and throwing in a speed module or whatever

**Comment by hail12pink** [comment]
this specifically is a bit difficult to implement on the technical side unless we make like a `SoundPlayer` module or something that we call to play sounds so the game knows what objects sounds belong to and what their default volumes and other properties are supposed to be

**Comment by dogranger1** [comment]
why not make it such that something like welding a piece of Cloth to a part would decrease that part's sound output and the size / surface area of the part affects how much noise is reduced, rather than having a magical ability to add a component to a part that reduces its sound output

**Comment by orbspiral** [comment]
> this is assuming multiple components of the same type can be installed onto the same part, i guess they probably can't but it shouldn't be that complex and i think future part modifications(and possibly upgrades?) like this would work neatly and be very intuitive with the component system.

you wouldn't need to have multiple of the same component. the strength of the muffler would be a configurable that can be clamped.

**Comment by hail12pink** [comment]
> components are free though? adding two of the same one is still free

wait i might be stupid i thought they were part-base
