### ISSUE TITLE
Name lock groups

### ISSUE THREAD

**Issue by sweetboss12512** [Eggs-D-Studios/wos-issues#584]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

would be nice

### What do you propose? What should change, or what should be added?

be able to change "Group \<number\>" to something else

**Comment by hail12pink** [comment]
idk i feel like it's easy enough to associate these things in your memory so it's not that much of a priority
