### ISSUE TITLE
EnergyShield Bubble is indestructible

### ISSUE THREAD

**Issue by voidstonism** [Eggs-D-Studios/wos-issues#586]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

When on, the `EnergySheild` makes a energy bubble as expected. However when lasers or any type of energy weapons are point at said bubble the health of the bubble does not go down as shown below using the `:GetShieldHealth()` Method.
![Screenshot 2024-11-24 163507](https://github.com/user-attachments/assets/a21482ea-a5b2-4eb1-b610-f159568c9292)

![Screenshot 2024-11-24 164502](https://github.com/user-attachments/assets/e2c6aedb-35d4-4251-90c2-8512d7e3ac66)

### How can we reproduce this bug?

Power an `EnergySheild`, point energy weapons of any kind at the energy bubble (`Laser`/`EnergyGuns` perferably)
Continuiously measure the Health of the shield with `:GetShieldHealth()`

### Frequency

Always

**Comment by hail12pink** [comment]
lasers and energyguns aren't supposed to damage energyshields

**Comment by hail12pink** [comment]
![image psd](https://github.com/user-attachments/assets/bb633d49-34cf-4411-afb5-dbc3f1f3288b)
