### ISSUE TITLE
`rawget` and `rawset` are missing

### ISSUE THREAD

**Issue by RiskoZoSlovenska** [Eggs-D-Studios/wos-issues#588]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

The `rawget` and `rawset` functions are missing from the Pilot environment. These functions aren't super obscure and some external libraries (e.g. the Signal library) may not work without them, not to mention that they're useful even by themselves. At the moment, players are forced to use hacky workarounds such as unsetting+resetting metatables.

### How can we reproduce this bug?

```lua
print(rawset, rawget) --> nil nil
```

### Frequency

Always

**Comment by hail12pink** [comment]
i think this obviously isnt a _bug_

**Comment by hail12pink** [comment]
i think this obviously isnt a _bug_

**Comment by RiskoZoSlovenska** [comment]
I may be mistaken, but a somewhat significant piece of the global environment missing sounds more like a bug than merely an unimplemented feature to me

**Comment by Hexcede** [comment]
These are intentionally not there to make sandboxing easier and more performant. I don't plan on adding these any time soon if ever.

> a somewhat significant piece of the global environment missing

They are two functions that bypass `__index` and `__newindex`, you are not really missing anything significant.

**Comment by RiskoZoSlovenska** [comment]
Wouldn't simply adding a `__meta` field to all the metatables that shouldn't be accessed by the user suffice for sandboxing?

If not, could Pilot at least provide official workaround functions (which unset the metatable, perform the operation, and then set it again) so that external libraries used by users don't break (as badly)?

**Comment by hail12pink** [comment]
> Wouldn't simply adding a `__meta` field to all the metatables that shouldn't be accessed by the user suffice for sandboxing?
> 
> 
> 
> If not, could Pilot at least provide official workaround functions (which unset the metatable, perform the operation, and then set it again) so that external libraries used by users don't break (as badly)?

using those functions in that context are weird practice anyways
