### ISSUE TITLE
Couplers decoupling on warp

### ISSUE THREAD

**Issue by SPECTERIN** [Eggs-D-Studios/wos-issues#598]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Everytime you warp there is chance for Couplers to uncouple and be left behind upon warping
It's getting annoying.
(to get around this issue I had to lock the couplers in using clipped parts)

### How can we reproduce this bug?

 Warp with any coupled item (can be in space or planet or in any environment)

### Frequency

Most of the time

**Comment by dogranger1** [comment]
Copy of https://github.com/Eggs-D-Studios/wos-issues/issues/399

**Comment by SPECTERIN** [comment]
How do I delete it? I searched "Coupler" on the searchbar here before and nothing was found?

**Comment by dogranger1** [comment]
> How do I delete it? I searched "Coupler" on the searchbar here before and nothing was found?
> 
> edit: i typed coupler wrong before. mb

You can close the issue at the bottom where you can post new comments.
