### ISSUE TITLE
Dev teleporters and other developer locked parts in the test zone are destructible

### ISSUE THREAD

**Issue by NobodyImportant64** [Eggs-D-Studios/wos-issues#599]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

With enough energy bombs you can destroy items locked by THE DEVELOPERS including the teleporters to space and earth in the test zone but also all other dev locked items like the space station.

### How can we reproduce this bug?

1. Teleport to 'space'
2. Spawn and detonate a large amount of energy bombs within the space structure
3. The structure will take damage/be destroyed instead of being invulnerable

### Frequency

Always

**Comment by hail12pink** [comment]
this is not really a bug they only have 70 durability and 90% explosion resistance
