### ISSUE TITLE
Resizable gyros.

### ISSUE THREAD

**Issue by articlize** [Eggs-D-Studios/wos-issues#60]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Development (Unstable)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

too large for smaller applications.

### What do you propose? What should change, or what should be added?

currently most useful part in the game, but would be far more useful if they could be resized for smaller applications.

**Comment by Hexcede** [comment]
I don't think I am ever going to make gyros resizable because they are already more than small enough. There are not really valid "smaller applications" because at that point whatever you're making is tiny, and things that are that tiny are really annoying to deal with.
