### ISSUE TITLE
Part drift, and a problem with welding ship parts together.

### ISSUE THREAD

**Issue by MisterCheeeez** [Eggs-D-Studios/wos-issues#600]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

I'll be happily building my ship, so excited, and finish it, but when I test it, it is forcibly anchored to absolutely nothing.

This has happened a multitude of times, and whenever I _do_ get the ship to move, it slowly separates itself into pieces, and I can't put any more parts on it or try to fix the mystery shredding.

I have dubbed the ship parts, especially wedges, getting slowly ripped apart by 0.001 stud gaps, "Mystery shredding"

### How can we reproduce this bug?

1. Get a little grass post
2. Build a ship, but halfway through put a vehicle seat on it. Make sure it is on the grass post.
3. Delete the grass post.
The ship floats, and wont move!
If it does, then it slowly breaks apart.

### Frequency

Only sometimes

**Comment by NameTemplate** [comment]
the ship floating thing is likely to be weld corruption
but mystery shredding, i thought that was fixed? (previously labeled part shift)

**Comment by MisterCheeeez** [comment]
lol

**Comment by NameTemplate** [comment]
okay so i thought it welded to the air
then it's a saving issue, not weld corruption

**Comment by hail12pink** [comment]
does it happen on flat ground when the ship is at an angle

**Comment by MisterCheeeez** [comment]
yes but also when the ship is perfectly aligned

**Comment by MisterCheeeez** [comment]
any part that its touching gets welded on to it

**Comment by Hexcede** [comment]
> the ship floating thing is likely to be weld corruption but mystery shredding, i thought that was fixed? (previously labeled part shift)

The bugs you listed I already fixed, part of the problem is that naming these bugs is futile because there were or have been like 10 different instances of bugs like them

**Comment by Hexcede** [comment]
@MisterCheeeez If you could, open a support ticket in the Discord server so that I can check out your coordinate

**Comment by MisterCheeeez** [comment]
The post fizzled away and the bug has since been fixed. (mostly, with rare instances of build randomly shifting around)
