### ISSUE TITLE
microcontroller door improvement

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#604]
### Guidelines

- [ ] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Production)

### Topic

A programming feature (e.g. APIs, tweaks, changes, etc)

### Why are you making your suggestion?

i saw some guy saying that part.Door.Switch is read only and like. i think that you should probably be able to write to that. I did not actually check if this is the case but it probably is

### What do you propose? What should change, or what should be added?

make part.Door.Switch writable.

**Comment by Hexcede** [comment]
`part.Door` is not a thing, and it is writeable (via `Door/Switch` config path & `:GetComponent("Door").Switch`)
