### ISSUE TITLE
Why do long (newer) audio id's not work?

### ISSUE THREAD

**Issue by Lopsifromroblox** [Eggs-D-Studios/wos-issues#613]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Main (Production)

### What happened? What did you expect to happen?

Audio ID's with lots of digits like https://create.roblox.com/store/asset/114081526542617/ramielshort?pageNumber=1&pagePosition=0 will not play in speakers, but older (shorter) ones like https://create.roblox.com/store/asset/1848354536/Relaxed-Scene?pageNumber=1&pagePosition=0 do work.

### How can we reproduce this bug?

Choose any new audio idea with a lot of digits, like https://create.roblox.com/store/asset/119961578123425/ramiel-angel?pageNumber=1&pagePosition=0 and put the id in a speaker, then play that speaker (it wont play).

### Frequency

Always

**Comment by Hexcede** [comment]
@Lopsifromroblox This has nothing to do with the length of the audio ID, WoS does not have permission to play the audio you listed.

**Comment by Hexcede** [comment]
![image](https://github.com/user-attachments/assets/a1431185-9220-4f05-80ff-bc9b66b60ba2)
