### ISSUE TITLE
Every stud of "Light" and "LightTube" should emit light

### ISSUE THREAD

**Issue by Apethesis** [Eggs-D-Studios/wos-issues#63]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Development (Unstable)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

As i feel light is kind of dumb if it just emits from the middle, it would be nice for it to emit light from every stud it has and it SHOULDNT be a lag issue since light has limited malleability.

### What do you propose? What should change, or what should be added?

As stated above, Light and LightTube should emit light from every stud the part contains. Currently it does not appear to do so, viewable easily with a reflective part and Future lighting (bloxstrap, probably unstable, etc).

**Comment by Hexcede** [comment]
This is a Roblox limitation, there is not any fine control over which space emits light or something so if Roblox isn't displaying the lights correctly then Roblox isn't displaying the lights correctly and there's not really much I could do about that.

Also, the amount of space that emits light is not really the main source of lag, it's more the number of light sources.
