### ISSUE TITLE
SpecialMesh AR Issue

### ISSUE THREAD

**Issue by tmenna1** [Eggs-D-Studios/wos-issues#65]
### Guidelines

- [x] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

you said 

"I guess SpecialMesh isn't in the instance allow list anymore"

![image](https://github.com/Eggs-D-Studios/wos-issues/assets/110530634/2c7341f5-1a15-49df-9242-d713d5261855)

### How can we reproduce this bug?

 1. Use this script
 ```
local ARController = GetPartFromPort(1,"ARController")
ARController:ClearElements()
local part = ARController:CreateElement("Part", {Size=Vector3.new(5,5,5),Transparency=0.5,Material=Enum.Material.Neon,CFrame=Microcontroller.CFrame}, "3D")

local mesh = ARController:CreateElement("SpecialMesh", {
    MeshType = Enum.MeshType.FileMesh;
    MeshId = "rbxassetid://12733085019";
}, "3D")

mesh.Parent = part

while true do
    wait(5)
end
```

 Parts needed: 
 Microcontroller, Port, ,AR screen, power supplies

### Frequency

Always

**Comment by Hexcede** [comment]
This isn't a bug, should be a feature request instead. But `SpecialMesh` will be added to the allow list.
