### ISSUE TITLE
game does not load

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#66]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

i joined the game and then im stuck on a black screen and the game says loading progress is 0% (although you did say you intentionally removed the functionality for that)

### How can we reproduce this bug?

attempt to play the game

### Frequency

Always

**Comment by NameTemplate** [comment]
this is now fixed. (i checked)
