### ISSUE TITLE
Only let accounts that aged more than 30 days to join to prevent griefers/ban evader

### ISSUE THREAD

**Issue by khaopong23TH4** [Eggs-D-Studios/wos-issues#73]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Main (Stable)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

It will certainly stop ban evader for an amounts of time. They will have to wait before joining again meaning we can do something peacefully in testing zone.

### What do you propose? What should change, or what should be added?

Let only accounts aged over 30 days to join, that's all.

**Comment by Hexcede** [comment]
This is already a thing
