### ISSUE TITLE
mining makes it really hot

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#76]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

when i mine a lot with my pickaxe it starts to get really hot

### How can we reproduce this bug?

mine stuff

### Frequency

Always

**Comment by Hexcede** [comment]
This is fixed (next time I publish)

**Comment by Hexcede** [comment]
Fixed
