### ISSUE TITLE
it is always very dark in space

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#78]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

it is very dark in space. Even in orbit around planets. I can even see what is suppost to be the sun, but it is still dark.
![sun space dark](https://github.com/Eggs-D-Studios/wos-issues/assets/85601187/5dbe508c-2977-4592-9d13-f9b7b31b75c9)

### How can we reproduce this bug?

go to space.

### Frequency

Always

**Comment by Hexcede** [comment]
This should be resolved, let me know if it isn't

**Comment by L5108313** [comment]
oh um @Hexcede IT ISNt this still happens
