### ISSUE TITLE
some energy projectiles completely ignore energysheilds

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#85]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

auto laser, burst laser, and plasmacannon projectiles go straight through energysheilds

### How can we reproduce this bug?

shoot autolaser at esheild

### Frequency

Always

**Comment by Hexcede** [comment]
This is intended behaviour (idk why but it is)
