### ISSUE TITLE
game is not actually 60 tps??

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#86]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

looking at the f3 menu, it is showing ~30 tps. I have just joined testing zone and there is nothing happening.

### How can we reproduce this bug?

look at f3

### Frequency

Always

**Comment by Hexcede** [comment]
This is called lag
