### ISSUE TITLE
alien capital bins spawn outside the ship

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#87]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

![alien capital bins](https://github.com/Eggs-D-Studios/wos-issues/assets/85601187/eab3ffb9-98f5-47d7-b4db-289ae546a176)

### How can we reproduce this bug?

look at alien capital

### Frequency

Always

**Comment by Hexcede** [comment]
This should be resolved, let me know if it isn't
