### ISSUE TITLE
aliens do not load shapes correctly

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#88]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

aliens load shapes as the template part instead of a shaped actual part.

### How can we reproduce this bug?

look at aliens

### Frequency

Always

**Comment by Hexcede** [comment]
This should be resolved, let me know if it isn't
