### ISSUE TITLE
Boiler that really boils water with heat

### ISSUE THREAD

**Issue by NewbieDis** [Eggs-D-Studios/wos-issues#90]
### Guidelines

- [X] I checked for duplicate suggestions
- [X] My suggestion intends to add or improve something

### Version

Development (Unstable)

### Topic

A game mechanic (e.g. a part, a feature, etc)

### Why are you making your suggestion?

You can see, reactors can be this part(the boiler).
reactor can make steam with environment heat.
![image](https://github.com/Eggs-D-Studios/wos-issues/assets/154730986/43aff215-17fe-4d02-b86a-bcd3789f6323)
this picture isnt unstable, but you can see its able to make heat and make steam without any uranium!
its making steam with **coal**!

so, how about adding part which makes steam with water and heat.
or reactors will keep being cheap infinity energy resource.

instead of cheap, how about making infinity energy resource as _expensive_.

like costing exotic matter to make it.

### What do you propose? What should change, or what should be added?

**adding a** 
_HeatBoiler (not coal boiler)_
receives heat from every possible ways.
and makes steam if water connected.

**Comment by Hexcede** [comment]
That is already how boilers work in unstable
