### ISSUE TITLE
Sorter has weird behaviors

### ISSUE THREAD

**Issue by L5108313** [Eggs-D-Studios/wos-issues#96]
### Guidelines

- [X] I checked for duplicate bug reports
- [X] I tried to find a way to reproduce the bug

### Version

Development (Unstable)

### What happened? What did you expect to happen?

Sorters have a very weird and inconsistant transfer rate. When the value is inf/obscenely large (2000000) they instantly send everything. When the value is normal, higher numbers seem to be better, but not linearly. A transfer rate of 200 gave 123 in the same time a transfer rate of 100 gave 82. When the values are from 89-30 the transfer rate seems to be the same, and when the values are below 30 nothing happens.

### How can we reproduce this bug?

use a sorter

### Frequency

Always

**Comment by L5108313** [comment]
![sorter tester machine](https://github.com/Eggs-D-Studios/wos-issues/assets/85601187/7057a0de-7170-4541-b07a-16c175668bbc)
also heres the setup i was using to test this because i think its kindof neat

**Comment by Hexcede** [comment]
This should be resolved, let me know if it isn't
